// Plan 15: the model of "More things to do here" (UI-SPEC 7.3 ActionList). Pure: it takes the
// `act` closures a body gets (never `$`, never an atom) and plain text, and gives back plain data.
//
// Where the rows come from: the mod's guarded derived copies of data/command-registry.json and
// data/section-job-canon.json (assets/, kept byte-equal by tests/test-369.26-registry-sync.cjs),
// read at run time through `act.readAsset`. No command name, count or reason is written into the
// mod. The registry is regenerated by the born-wired build and is never edited here.
//
// Which rows: a methodology command is not listed (UI-SPEC 7.3: it stays in the transcript and is
// reached from the next-step button). The registry marks it with the `body_shape` value
// "methodology"; every other row is listed, whatever its destination, because a press only adds
// the command to the prompt box. A row with no one-line reason (`jtbd_summary` blank or missing)
// is left out: the list says why a thing is worth doing, and a row with no why would be a bare name.
//
// What a folder means: the folder filter maps a folder (a section name as the job canon spells it)
// to its job (and its second job when the canon names one), and a command to its jobs through its
// `serves_jtbd` list. A command matches a folder when one of its jobs is one of the folder's jobs.
//
// Never read here: `hitl_shape`. A press adds text for the person to submit; the mod adds or
// removes no confirmation.
import type { Actions } from '../types'
import type { BodySlice } from '../kit'

// One listed command. `command` is the registry's text as stored (it already carries the slash and
// the namespace); `summary` is its one-line plain reason; `jobs` are the jobs it serves.
export type ActionRow = { command: string; summary: string; jobs: string[] }

// A folder (as the canon spells it) to the jobs it stands for, first the main job.
export type JobCanon = { [folder: string]: string[] }

export type ActionsLoad = { state: 'ok'; rows: ActionRow[]; canon: JobCanon } | { state: 'unavailable' }

// The filter value that means "every folder" (the P121 option). A folder name never equals it.
export const ALL_FOLDERS = '*'

// The marker the registry puts on a methodology command in `body_shape`.
const METHODOLOGY = 'methodology'

function isObj(x: unknown): x is { [key: string]: unknown } {
  return typeof x === 'object' && x !== null && !Array.isArray(x)
}

function nonBlank(x: unknown): x is string {
  return typeof x === 'string' && x.trim().length > 0
}

// Build the list from the text of the two files. Never throws: a file that does not parse or does
// not have the expected shape reads as unavailable (M03).
export function parseActions(registryText: string, canonText: string): ActionsLoad {
  let registry: unknown
  let canonJson: unknown
  try {
    registry = JSON.parse(registryText)
    canonJson = JSON.parse(canonText)
  } catch {
    return { state: 'unavailable' }
  }
  if (!isObj(registry) || !Array.isArray(registry.commands)) return { state: 'unavailable' }
  if (!isObj(canonJson) || !isObj(canonJson.sections)) return { state: 'unavailable' }

  const canon: JobCanon = {}
  for (const folder of Object.keys(canonJson.sections)) {
    const entry = canonJson.sections[folder]
    if (!isObj(entry) || !nonBlank(entry.job_id)) continue
    const jobs = [entry.job_id]
    if (nonBlank(entry.secondary_job_id)) jobs.push(entry.secondary_job_id)
    canon[folder] = jobs
  }

  const rows: ActionRow[] = []
  for (const raw of registry.commands) {
    if (!isObj(raw)) continue
    if (!nonBlank(raw.command) || !nonBlank(raw.body_shape)) continue
    if (raw.body_shape.trim() === METHODOLOGY) continue
    if (!nonBlank(raw.jtbd_summary)) continue
    const jobs = Array.isArray(raw.serves_jtbd) ? raw.serves_jtbd.filter((j): j is string => nonBlank(j)) : []
    rows.push({ command: raw.command, summary: raw.jtbd_summary.trim(), jobs })
  }
  return { state: 'ok', rows, canon }
}

// Read both assets and build the list. Never throws: a read that fails reads as unavailable.
export async function loadActions(act: Pick<Actions, 'readAsset'>): Promise<ActionsLoad> {
  try {
    const registryText = await act.readAsset('command-registry.json')
    const canonText = await act.readAsset('section-job-canon.json')
    return parseActions(registryText, canonText)
  } catch {
    return { state: 'unavailable' }
  }
}

// The rows a folder filter lets through: every row for ALL_FOLDERS, the rows that serve one of the
// folder's jobs for a folder the canon knows, and none for a folder it does not know (nothing is
// invented to fill the gap).
export function filterRows(rows: readonly ActionRow[], canon: JobCanon, folder: string): ActionRow[] {
  if (folder === ALL_FOLDERS) return [...rows]
  const jobs = canon[folder]
  if (jobs === undefined) return []
  return rows.filter((row) => row.jobs.some((job) => jobs.includes(job)))
}

// The canon's folder a place name stands for: the name as stored when the canon has it, else the
// same name with a leading number and its separator taken off ("03_funding" is "funding"). Null
// when the canon does not know the folder.
export function canonFolder(canon: JobCanon, name: string | null): string | null {
  if (name === null) return null
  if (canon[name] !== undefined) return name
  const trimmed = name.trim().toLowerCase().replace(/^\d+[\s_.-]+/, '').replace(/[\s_]+/g, '-')
  return canon[trimmed] !== undefined ? trimmed : null
}

// The filter in force: the person's pick when they made one, else the current folder when the
// canon knows it, else every folder.
export function effectiveFilter(canon: JobCanon, picked: string | null, currentFolder: string | null): string {
  if (picked !== null && (picked === ALL_FOLDERS || canon[picked] !== undefined)) return picked
  return canonFolder(canon, currentFolder) ?? ALL_FOLDERS
}

function isRow(x: unknown): x is ActionRow {
  return isObj(x) && nonBlank(x.command) && nonBlank(x.summary) && Array.isArray(x.jobs) && x.jobs.every((j) => typeof j === 'string')
}

function isCanon(x: unknown): x is JobCanon {
  return isObj(x) && Object.keys(x).every((k) => Array.isArray(x[k]) && (x[k] as unknown[]).every((j) => typeof j === 'string'))
}

export function isActionsLoad(x: unknown): x is ActionsLoad {
  if (!isObj(x)) return false
  if (x.state === 'unavailable') return true
  return x.state === 'ok' && Array.isArray(x.rows) && x.rows.every(isRow) && isCanon(x.canon)
}

// The Room slice of the `body` state, narrowed: whether the list is open, the cached load (null
// when it has not been read yet) and the folder the person picked (null when they have not).
export type ActionsState = { open: boolean; load: ActionsLoad | null; picked: string | null }

export function readActionsState(slice: BodySlice): ActionsState {
  return {
    open: slice.actionsOpen === true,
    load: isActionsLoad(slice.actionRows) ? slice.actionRows : null,
    picked: typeof slice.actionFilter === 'string' ? slice.actionFilter : null,
  }
}

// The m key and the P52 or P53 button: close an open list; open a closed one, reading the registry
// the first time (and again when the last read failed). Runs in a press handler, so it may write.
export async function toggleActions(act: Pick<Actions, 'patch' | 'readAsset'>, state: ActionsState): Promise<void> {
  if (state.open) {
    await act.patch('room', { actionsOpen: false })
    return
  }
  await act.patch('room', { actionsOpen: true })
  if (state.load !== null && state.load.state === 'ok') return
  const load = await loadActions(act)
  await act.patch('room', { actionRows: load })
}

// Pick a folder in the filter. A value the canon does not know and that is not "all" is ignored.
export async function pickFolder(act: Pick<Actions, 'patch'>, load: ActionsLoad | null, value: string): Promise<void> {
  if (load === null || load.state !== 'ok') return
  if (value !== ALL_FOLDERS && load.canon[value] === undefined) return
  await act.patch('room', { actionFilter: value })
}
