'use strict';

// B1: local verification records for claim nodes.
//
// A verification record answers "what was this claim checked against?" It is
// evidence of a checking action, not a truth promotion. Claims remain at their
// existing review_status until a human gate promotes them.
//
// Phase 358-01 (Rome B1): adds the ONE ordered rung constant, rung and
// checked_by_id on the record, the sticky "disputed" rule, a claim-view
// reader, a claims-list reader, a room portrait broken out by rung, and the
// plain-text render helpers the CLI (358-03) and the MCP tools (358-04) both
// print. This file is the only write door (writeClaimProperties -> insertNode)
// and the only place the rung labels are written (Canon Part 9, Part 8).
//
// NO em-dashes in this file (CLAUDE.md HARD RULE); hyphens only.

const { insertNode } = require('../node-insert.cjs');

const CHECK_STATUSES = Object.freeze(new Set([
  'unchecked', 'checked', 'disputed', 'inconclusive',
]));
const AGAINST_KINDS = Object.freeze(new Set([
  'artifact', 'source', 'observation', 'person', 'experiment',
]));
const METHODS = Object.freeze(new Set(['read', 'compare', 'observe', 'test', 'ask']));
const RESULTS = Object.freeze(new Set(['supports', 'contradicts', 'inconclusive']));
const ACTORS = Object.freeze(new Set(['user', 'system']));

// TODO(358): replace with the paper author's verification hierarchy from The Orientation Problem.
// Provisional source: what-ai-cannot-know.vercel.app Part V practice 3. Rung 1 is lowest; rung number = index + 1.
// NOT the problem-type rung vocabulary (lib/core/strategy/rung-vocabulary.cjs); never mix or import the two.
const VERIFICATION_RUNGS = Object.freeze([
  Object.freeze({ id: 'own_intuition', label: 'Your own intuition' }),
  Object.freeze({ id: 'model_counter_argument', label: 'A counter-argument generated by the model' }),
  Object.freeze({ id: 'database_or_document', label: 'A database or a document' }),
  Object.freeze({ id: 'primary_source', label: 'A primary source' }),
  Object.freeze({ id: 'dissenting_person', label: 'A person who disagrees with you' }),
]);

// rungInfo(n) -- 1-based; null when n is not an integer 1..VERIFICATION_RUNGS.length.
function rungInfo(n) {
  if (!Number.isInteger(n) || n < 1 || n > VERIFICATION_RUNGS.length) return null;
  const entry = VERIFICATION_RUNGS[n - 1];
  return { rung: n, id: entry.id, label: entry.label };
}

// STATUS_NOTES / CONFIRMATION_NOTES -- the ONE place these labels are written,
// so the CLI and Desktop always show the same words, and "checked" can never
// be read as "confirmed" (Separation from approval, Canon Part 12).
const STATUS_NOTES = Object.freeze({
  unchecked: 'no checking record yet',
  checked: 'checked is not the same as confirmed',
  disputed: 'at least one check contradicts this claim; it stays disputed until a person marks the contradiction answered',
  inconclusive: 'the latest check was inconclusive',
});
const CONFIRMATION_NOTES = Object.freeze({
  proposed: 'Proposed. Only a person can confirm this claim. A checking record never confirms it.',
  confirmed: 'Confirmed by a person.',
});
function confirmationNote(reviewStatus) {
  return Object.prototype.hasOwnProperty.call(CONFIRMATION_NOTES, reviewStatus)
    ? CONFIRMATION_NOTES[reviewStatus]
    : 'Only a person changes this status. A checking record never does.';
}

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function cleanString(value, max) {
  if (typeof value !== 'string' || value.length === 0 || value.length > max) return '';
  return value;
}

function readNode(db, claimId) {
  try {
    return db.prepare('SELECT id, type, properties, review_status FROM nodes WHERE id = ?').get(claimId);
  } catch (_e) {
    return null;
  }
}

function parseProperties(row) {
  try {
    const parsed = JSON.parse(row && row.properties ? row.properties : '{}');
    return isPlainObject(parsed) ? parsed : {};
  } catch (_e) {
    return {};
  }
}

function writeClaimProperties(db, row, properties) {
  const parsed = JSON.stringify(properties);
  try {
    insertNode(db, row.id, row.type, parsed, {
      source_path: 'verification:' + row.id,
      created_by: 'system',
      epistemic_type: typeof properties.epistemic_type === 'string'
        ? properties.epistemic_type : 'extracted_fact',
    });
    return { ok: true };
  } catch (e) {
    return { ok: false, reason: 'verification_write_failed', detail: String(e.message || '').slice(0, 100) };
  }
}

// normalizeRecords(records) -- keeps only plain objects whose result is a
// member of the closed RESULTS enum. Malformed stored entries are ignored by
// every reader so a corrupted row degrades gracefully instead of throwing.
function normalizeRecords(records) {
  if (!Array.isArray(records)) return [];
  return records.filter((r) => isPlainObject(r) && RESULTS.has(r.result));
}

// deriveCheckStatus(records) -- the ONLY place check status is computed. A
// contradicts record disputes the claim UNTIL a later record carries
// resolves_dispute:true with checked_by:'user' (the "Disputed sticks" /
// "Who checked" navigator rulings, 2026-09-23). A plain (non-resolving)
// supports after a contradicts never clears the dispute.
function deriveCheckStatus(records) {
  const normalized = normalizeRecords(records);
  if (normalized.length === 0) return 'unchecked';
  let lastResolveIndex = -1;
  for (let i = 0; i < normalized.length; i += 1) {
    if (normalized[i].resolves_dispute === true && normalized[i].checked_by === 'user') {
      lastResolveIndex = i;
    }
  }
  for (let i = lastResolveIndex + 1; i < normalized.length; i += 1) {
    if (normalized[i].result === 'contradicts') return 'disputed';
  }
  const last = normalized[normalized.length - 1];
  return last.result === 'inconclusive' ? 'inconclusive' : 'checked';
}

/**
 * Append one checking event to a claim's additive properties JSON.
 * Required fields are generic handles or closed enums. Free-form notes are
 * represented by note_handle, so claim prose never becomes graph metadata.
 * rung, checked_by_id and resolves_dispute are all optional and additive;
 * legacy callers with none of the three keep working unchanged.
 */
function recordClaimVerification(db, params) {
  if (!isPlainObject(params)) return { ok: false, reason: 'invalid_params' };
  const claimId = cleanString(params.claim_id, 512);
  const againstId = cleanString(params.against_id, 512);
  const againstKind = cleanString(params.against_kind, 32);
  const method = cleanString(params.method, 32);
  const result = cleanString(params.result, 32);
  const checkedBy = cleanString(params.checked_by || 'user', 16);
  if (!claimId || !againstId) return { ok: false, reason: 'missing_handle' };
  if (!AGAINST_KINDS.has(againstKind)) return { ok: false, reason: 'invalid_against_kind' };
  if (!METHODS.has(method)) return { ok: false, reason: 'invalid_method' };
  if (!RESULTS.has(result)) return { ok: false, reason: 'invalid_result' };
  if (!ACTORS.has(checkedBy)) return { ok: false, reason: 'invalid_checked_by' };

  let rungRec = null;
  if (params.rung !== undefined && params.rung !== null) {
    rungRec = rungInfo(params.rung);
    if (!rungRec) return { ok: false, reason: 'invalid_rung' };
  }

  let checkedById = '';
  if (params.checked_by_id !== undefined && params.checked_by_id !== null && params.checked_by_id !== '') {
    checkedById = cleanString(params.checked_by_id, 128);
    if (!checkedById) return { ok: false, reason: 'invalid_checked_by_id' };
  }

  let resolvesDispute = false;
  if (params.resolves_dispute !== undefined) {
    if (typeof params.resolves_dispute !== 'boolean') return { ok: false, reason: 'invalid_resolves_dispute' };
    resolvesDispute = params.resolves_dispute;
    if (resolvesDispute) {
      if (checkedBy !== 'user') return { ok: false, reason: 'resolution_requires_person' };
      if (result === 'contradicts') return { ok: false, reason: 'invalid_resolution' };
    }
  }

  // CR-01: node:sqlite's DatabaseSync has no nested-transaction support (same
  // ownership idiom as lib/core/navigation/ranker-weights.cjs). A caller who
  // already opened a transaction on this handle owns COMMIT/ROLLBACK; this
  // function only opens/closes ITS OWN transaction when none is already open,
  // so a lost update under concurrent checks (T-358-04, Cowork) never happens
  // and a caller's unrelated pending writes are never discarded here.
  const owns = db.isTransaction !== true;
  if (owns) db.exec('BEGIN IMMEDIATE');
  try {
    const row = readNode(db, claimId);
    if (!row || row.type !== 'claim') {
      if (owns) db.exec('ROLLBACK');
      return { ok: false, reason: 'claim_not_found' };
    }
    const props = parseProperties(row);
    const verification = isPlainObject(props.verification) ? props.verification : {};
    const records = Array.isArray(verification.records) ? verification.records.slice() : [];

    if (resolvesDispute && deriveCheckStatus(records) !== 'disputed') {
      if (owns) db.exec('ROLLBACK');
      return { ok: false, reason: 'no_dispute_to_resolve' };
    }

    const checkedAt = cleanString(params.checked_at, 64) || new Date().toISOString();
    const record = {
      against_id: againstId,
      against_kind: againstKind,
      method: method,
      result: result,
      checked_by: checkedBy,
      checked_at: checkedAt,
    };
    const noteHandle = cleanString(params.note_handle, 512);
    if (noteHandle) record.note_handle = noteHandle;
    if (rungRec) {
      record.rung = params.rung;
      record.rung_label = rungRec.label;
    }
    if (checkedById) record.checked_by_id = checkedById;
    if (resolvesDispute) record.resolves_dispute = true;

    records.push(record);
    props.verification = { status: deriveCheckStatus(records), records: records };

    const write = writeClaimProperties(db, row, props);
    if (!write.ok) {
      if (owns) db.exec('ROLLBACK');
      return write;
    }
    if (owns) db.exec('COMMIT');
    return { ok: true, claim_id: claimId, review_status: row.review_status, verification: props.verification };
  } catch (e) {
    if (owns) db.exec('ROLLBACK');
    throw e;
  }
}

/**
 * readClaimVerification(db, claimId) -- the claim view. Confirmation
 * (review_status) and the checking record are returned side by side, labeled
 * so "checked" is never read as "confirmed" (AT2, AT4).
 */
function readClaimVerification(db, claimId) {
  const row = readNode(db, claimId);
  if (!row || row.type !== 'claim') return { ok: false, reason: 'claim_not_found' };
  const props = parseProperties(row);
  const verification = isPlainObject(props.verification) ? props.verification : {};
  const storedRecords = Array.isArray(verification.records) ? verification.records : [];
  const status = deriveCheckStatus(storedRecords);
  const records = storedRecords.filter(isPlainObject).map((r) => {
    const copy = Object.assign({}, r);
    let display = 'rung unknown';
    if (Number.isInteger(copy.rung) && copy.rung >= 1) {
      const info = rungInfo(copy.rung);
      const label = typeof copy.rung_label === 'string' && copy.rung_label.length > 0
        ? copy.rung_label
        : (info ? info.label : 'label not on file');
      display = 'rung ' + copy.rung + ' (' + label + ')';
    }
    copy.rung_display = display;
    return copy;
  });
  return {
    ok: true,
    claim: {
      claim_id: row.id,
      text: typeof props.text === 'string' ? props.text : '',
      knowledge_type: typeof props.knowledge_type === 'string' ? props.knowledge_type : '',
      confirmation: {
        review_status: row.review_status,
        note: confirmationNote(row.review_status),
      },
      standing: claimStanding(db, row.id).standing,
      checking_record: {
        status: status,
        status_note: STATUS_NOTES[status],
        records_total: records.length,
        records: records,
      },
    },
  };
}

// ---------------------------------------------------------------------------
// Phase 365 B2: the ONE standing reader and the ONE provisional words map.
//
// "Standing" answers a different question than a declared rung: not "what did
// the caller say the check was", but "what does the room's own structure show
// the claim was checked against". It is computed from the claim's OUTBOUND
// provenance edges and its stored records only (D-03, D-24). Nothing here
// writes a node, an edge or an event (Canon Part 9), nothing reaches the
// network (Part 8), and no model computes or grades a standing.
//
// D-24: Phase 365.1 replaces ONLY the body of claimStanding with an edge-derived
// rung. Every surface reads this function, so that swap changes nothing else.
// ---------------------------------------------------------------------------

const STANDING_IDS = Object.freeze(['located_source', 'source_edge', 'model_only', 'none']);

// PROVISIONAL(365): wording is frozen only after the paper author ratifies the ladder (data/verification-ladder.json)
// Words describe what was DONE, never how sure anyone felt (Canon Part 12). A low
// standing is not a failure: most confirmed claims sitting low is the fix working.
const STANDING_WORDS = Object.freeze({
  located_source: Object.freeze({
    label: 'checked against a located part of a source outside the conversation',
    checked_against: 'a located part of a source outside the conversation',
    moves_when: 'a person with standing checks it (the room cannot record that yet)',
  }),
  source_edge: Object.freeze({
    label: 'checked against a source document outside the conversation (a link and a retrieval date)',
    checked_against: 'a source document outside the conversation',
    moves_when: 'the exact part of a primary source that decides it is recorded (a page, section, DOI or clause)',
  }),
  model_only: Object.freeze({
    label: 'recorded as checked only by asking a model',
    checked_against: "a model's answer only, as recorded",
    moves_when: 'it is checked against a source document outside the conversation',
  }),
  none: Object.freeze({
    label: 'not checked yet',
    checked_against: 'nothing outside the conversation yet',
    moves_when: 'any check is recorded',
  }),
});

// PROVISIONAL(365): held claims are a review state, not a standing; the row shares the words map's wording rules.
const HELD_WORDS = Object.freeze({
  label: "held for evidence (approved below this room's floor)",
  moves_when: "a source is attached and it is approved again, or the room's floor is lowered in ROOM.md",
});

// D-03 implementation note (2026-10-01 ruling): D-03 says "at least one outbound
// edge"; the implementation narrows it to outbound PROVENANCE edges only.
// SOURCED_FROM is the evidence edge the research names (writeReasoningNode writes
// claim -> evidence SOURCED_FROM). DEPENDS_ON and ASSUMES are listed per the
// ruling but are not members of edges.cjs ALLOWED_EDGE_TYPES today, so they are
// inert until admitted. CONTRADICTS and every other non-provenance edge never
// satisfy the floor: a claim pointing at a source that contradicts it, or merely
// relates to it, has not been checked against it. Adding any other type (for
// example DERIVED_FROM) is a deliberate widening that needs a ruling.
const PROVENANCE_EDGE_TYPES = Object.freeze(new Set(['SOURCED_FROM', 'DEPENDS_ON', 'ASSUMES']));

// Floor ids are the DRAFT ladder ids in data/verification-ladder.json (D-02, D-22).
const FLOOR_IDS = Object.freeze(new Set([
  'unchecked', 'recall', 'model_internal', 'secondary_document', 'primary_source_located', 'person',
]));
// Provisional aliases (the v358 rung ids) map to the draft ids.
const FLOOR_ALIASES = Object.freeze({
  database_or_document: 'secondary_document',
  primary_source: 'primary_source_located',
  own_intuition: 'recall',
  model_counter_argument: 'model_internal',
  dissenting_person: 'person',
});
const DEFAULT_FLOOR_ID = 'secondary_document';
const FLOOR_WORDS = Object.freeze({
  unchecked: 'no check at all',
  recall: "the navigator's own recall",
  model_internal: "a model's answer",
  secondary_document: 'a source document',
  primary_source_located: 'the located part of a primary source',
  person: "a person's check",
});

function nonEmptyString(v) {
  return typeof v === 'string' && v.trim().length > 0;
}

// claimStanding(db, claimId) -- read-only; never throws.
function claimStanding(db, claimId) {
  const out = {
    claim_id: claimId,
    found: false,
    standing: 'none',
    located: false,
    source_node_ids: [],
    declared_max_rung: null,
    records_total: 0,
  };
  let row;
  try {
    row = db.prepare("SELECT id, type, properties FROM nodes WHERE id = ? AND type = 'claim'").get(claimId);
  } catch (_e) {
    return out;
  }
  if (!row) return out;
  out.found = true;

  const props = parseProperties(row);
  const verification = isPlainObject(props.verification) ? props.verification : {};
  const records = normalizeRecords(Array.isArray(verification.records) ? verification.records : []);
  out.records_total = records.length;
  let askSeen = false;
  for (const rec of records) {
    if (rec.method === 'ask') askSeen = true;
    if (Number.isInteger(rec.rung) && rec.rung >= 1) {
      if (out.declared_max_rung === null || rec.rung > out.declared_max_rung) out.declared_max_rung = rec.rung;
      const info = rungInfo(rec.rung);
      if (info && info.id === 'model_counter_argument') askSeen = true;
    }
  }

  // Outbound provenance edges only (never inbound, never other types).
  const types = Array.from(PROVENANCE_EDGE_TYPES);
  let edges = [];
  try {
    edges = db.prepare(
      'SELECT target, properties FROM edges WHERE source = ? AND type IN (' + types.map(() => '?').join(',') + ')'
    ).all(claimId, ...types) || [];
  } catch (_e) {
    edges = [];
  }
  const sourceIds = [];
  let located = false;
  for (const edge of edges) {
    let target;
    try {
      target = db.prepare('SELECT id, properties FROM nodes WHERE id = ?').get(edge.target);
    } catch (_e) {
      target = null;
    }
    if (!target) continue;
    const tp = parseProperties(target);
    if (!nonEmptyString(tp.url) || !nonEmptyString(tp.retrieved_at)) continue;
    if (sourceIds.indexOf(target.id) === -1) sourceIds.push(target.id);
    const ep = parseProperties(edge);
    if (nonEmptyString(tp.locator) || nonEmptyString(ep.locator)) located = true;
  }
  out.source_node_ids = sourceIds.slice(0, 10);
  if (sourceIds.length > 0) {
    out.standing = located ? 'located_source' : 'source_edge';
    out.located = located;
  } else if (askSeen) {
    out.standing = 'model_only';
  }
  return out;
}

// readStandingPortrait(db) -- read-only room counts by standing, for the pulled
// portrait (D-16). Separate from readVerificationPortrait on purpose: that
// reader's output is pinned byte-for-byte by the 358 suites. Counts only, never
// a score; held = claims whose review_status is needs_evidence.
function readStandingPortrait(db) {
  const out = {
    claims_by_standing: { located_source: 0, source_edge: 0, model_only: 0, none: 0 },
    held: 0,
    records_total: 0,
  };
  let rows;
  try {
    rows = db.prepare("SELECT id, review_status FROM nodes WHERE type = 'claim'").all();
  } catch (_e) {
    return out;
  }
  for (const row of rows || []) {
    const st = claimStanding(db, row.id);
    const key = Object.prototype.hasOwnProperty.call(out.claims_by_standing, st.standing) ? st.standing : 'none';
    out.claims_by_standing[key] += 1;
    out.records_total += st.records_total;
    if (row.review_status === 'needs_evidence') out.held += 1;
  }
  return out;
}

// readReadinessCounts(db) -- HARNESS-11 counting half (369.2-27, annex C16, brief test 22). Read-only counts of
// claims apart from every other confirmed node type, so "confirmed" never means "confirmed whitespace zones".
// The session review counted 137 confirmed nodes that were auto-generated whitespace zones while zero claims
// were confirmed. These field names are the contract plan 369.4's export banner reads; do not rename them.
//
// READINESS_CLAIM_TYPES are the claim node types: transitions.cjs:47 TRUTH_CLAIM_TYPES minus decision,
// opportunity, assumption and SyntheticExpert (those are other truth-bearing nodes, not claims). EvidenceClaim
// is excluded on purpose: it carries untrusted external web bytes and is non-promotable (transitions.cjs
// NON_PROMOTABLE), so it can never be a confirmed claim. Confirmed means review_status 'confirmed'.
// A db without review_status (a legacy room) answers zeros with schema_note 'no_review_status'. One SELECT, no
// write, over the caller's handle (a read-only handle is fine).
const READINESS_CLAIM_TYPES = Object.freeze(['claim', 'CausalClaim']);

function readReadinessCounts(db) {
  const out = { claims_total: 0, confirmed_claim_count: 0, confirmed_other_by_type: {}, confirmed_other_count: 0 };
  let rows;
  try {
    const cols = db.prepare('PRAGMA table_info(nodes)').all() || [];
    const hasStatus = cols.some((c) => c && c.name === 'review_status');
    if (!hasStatus) {
      out.schema_note = 'no_review_status';
      return out;
    }
    rows = db.prepare('SELECT type, review_status, COUNT(*) AS c FROM nodes GROUP BY type, review_status').all();
  } catch (_e) {
    out.schema_note = 'no_review_status';
    return out;
  }
  for (const row of rows || []) {
    const n = Number(row.c) || 0;
    const isClaim = READINESS_CLAIM_TYPES.indexOf(row.type) !== -1;
    const confirmed = row.review_status === 'confirmed';
    if (isClaim) {
      out.claims_total += n;
      if (confirmed) out.confirmed_claim_count += n;
    } else if (confirmed) {
      out.confirmed_other_by_type[row.type] = (out.confirmed_other_by_type[row.type] || 0) + n;
      out.confirmed_other_count += n;
    }
  }
  return out;
}

// standingMeetsFloor(standing, floorId) -> {met, requirement}
function standingMeetsFloor(standing, floorId) {
  const requirement = Object.prototype.hasOwnProperty.call(FLOOR_WORDS, floorId) ? FLOOR_WORDS[floorId] : '';
  const sourceLike = standing === 'source_edge' || standing === 'located_source';
  let met = false;
  switch (floorId) {
    case 'unchecked':
    case 'recall':
      met = true;
      break;
    case 'model_internal':
      met = standing === 'model_only' || sourceLike;
      break;
    case 'secondary_document':
      met = sourceLike;
      break;
    case 'primary_source_located':
      met = standing === 'located_source';
      break;
    default:
      met = false; // person (not recordable yet) and anything unknown fail shut
  }
  return { met: met, requirement: requirement };
}

/**
 * listClaimsForChecking(db, {query, limit}) -- a search-by-text list so an
 * officer in a new session can reopen a claim without knowing its id
 * (Pitfall 3). Newest first, case-insensitive substring match.
 */
function listClaimsForChecking(db, opts) {
  const options = isPlainObject(opts) ? opts : {};
  let query = typeof options.query === 'string' ? options.query.trim().toLowerCase() : '';
  if (query.length > 200) query = query.slice(0, 200);
  let limit = Number.isInteger(options.limit) ? options.limit : 20;
  if (limit < 1) limit = 1;
  if (limit > 100) limit = 100;
  // Phase 365: optional standing filter. A value outside STANDING_IDS fails shut
  // (no rows), never "all rows".
  const standingFilter = options.standing === undefined || options.standing === null ? null : options.standing;
  if (standingFilter !== null && STANDING_IDS.indexOf(standingFilter) === -1) {
    return { ok: true, total_matched: 0, claims: [] };
  }

  let rows;
  try {
    rows = db.prepare("SELECT id, properties, review_status FROM nodes WHERE type = 'claim' ORDER BY rowid DESC").all();
  } catch (_e) {
    return { ok: true, total_matched: 0, claims: [] };
  }

  const kept = [];
  for (const row of rows || []) {
    const props = parseProperties(row);
    const text = typeof props.text === 'string' ? props.text : '';
    if (query && !text.toLowerCase().includes(query) && !String(row.id).toLowerCase().includes(query)) continue;
    const standing = claimStanding(db, row.id).standing;
    if (standingFilter !== null && standing !== standingFilter) continue;
    kept.push({ row: row, props: props, text: text, standing: standing });
  }
  const totalMatched = kept.length;
  const claims = kept.slice(0, limit).map((entry) => {
    const verification = isPlainObject(entry.props.verification) ? entry.props.verification : {};
    const records = Array.isArray(verification.records) ? verification.records : [];
    const preview = entry.text.length <= 120 ? entry.text : entry.text.slice(0, 117) + '...';
    return {
      claim_id: entry.row.id,
      text_preview: preview,
      review_status: entry.row.review_status,
      checking_status: deriveCheckStatus(records),
      records_total: records.length,
      standing: entry.standing,
    };
  });
  return { ok: true, total_matched: totalMatched, claims: claims };
}

/**
 * Read the B1 room portrait. Counts are descriptive and deliberately are not
 * collapsed into a score or a truth verdict (Canon Part 12). Status is
 * ALWAYS re-derived from the stored records (never read from the legacy
 * status field), so old latest-wins data is re-read under the sticky rule.
 */
function readVerificationPortrait(db) {
  const recordsByRung = {};
  for (let i = 1; i <= VERIFICATION_RUNGS.length; i += 1) recordsByRung[String(i)] = 0;
  recordsByRung.unknown = 0;

  const out = {
    claims_total: 0,
    claims_unchecked: 0,
    claims_checked: 0,
    claims_disputed: 0,
    claims_inconclusive: 0,
    records_total: 0,
    records_by_result: { supports: 0, contradicts: 0, inconclusive: 0 },
    records_by_rung: recordsByRung,
  };
  let rows;
  try {
    rows = db.prepare("SELECT properties FROM nodes WHERE type = 'claim'").all();
  } catch (_e) {
    return out;
  }
  for (const row of rows || []) {
    out.claims_total += 1;
    const props = parseProperties(row);
    const verification = isPlainObject(props.verification) ? props.verification : {};
    const storedRecords = Array.isArray(verification.records) ? verification.records : [];
    const status = deriveCheckStatus(storedRecords);
    if (status === 'unchecked') out.claims_unchecked += 1;
    if (status === 'checked') out.claims_checked += 1;
    if (status === 'disputed') out.claims_disputed += 1;
    if (status === 'inconclusive') out.claims_inconclusive += 1;
    for (const record of normalizeRecords(storedRecords)) {
      out.records_total += 1;
      if (Object.prototype.hasOwnProperty.call(out.records_by_result, record.result)) {
        out.records_by_result[record.result] += 1;
      }
      if (Number.isInteger(record.rung) && record.rung >= 1) {
        const key = String(record.rung);
        out.records_by_rung[key] = (out.records_by_rung[key] || 0) + 1;
      } else {
        out.records_by_rung.unknown += 1;
      }
    }
  }
  return out;
}

// renderPortraitLines / renderClaimViewLines / renderClaimListLines -- the
// ONE place these render strings are written; the CLI (358-03) and the MCP
// tools (358-04) both print these lines verbatim. Plain ASCII, hyphens only,
// the word "verified" never appears (Separation from approval).
function renderPortraitLines(portrait, standingPortrait) {
  const lines = [];
  lines.push('Checking record across this room (counts only)');
  lines.push('  checked: ' + portrait.claims_checked);
  lines.push('  disputed: ' + portrait.claims_disputed);
  lines.push('  inconclusive: ' + portrait.claims_inconclusive);
  lines.push('  unchecked (no checking record yet): ' + portrait.claims_unchecked);
  lines.push('  claims in this room: ' + portrait.claims_total);
  lines.push(
    '  checks recorded: ' + portrait.records_total +
    ' (supports ' + portrait.records_by_result.supports +
    ', contradicts ' + portrait.records_by_result.contradicts +
    ', inconclusive ' + portrait.records_by_result.inconclusive + ')'
  );
  const rungKeys = Object.keys(portrait.records_by_rung || {})
    .filter((k) => k !== 'unknown')
    .sort((a, b) => Number(a) - Number(b));
  const byRungParts = rungKeys.map((k) => 'rung ' + k + ': ' + portrait.records_by_rung[k]);
  byRungParts.push('rung unknown: ' + (portrait.records_by_rung.unknown || 0));
  lines.push('  checks by rung: ' + byRungParts.join(', '));
  // Phase 365 (D-16): the optional second argument adds one row per standing and
  // the held row, each naming what would move it. One argument renders exactly
  // the 358 lines. The closing line stays last.
  if (isPlainObject(standingPortrait) && isPlainObject(standingPortrait.claims_by_standing)) {
    lines.push("What this room's claims were checked against");
    STANDING_IDS.forEach((id) => {
      const n = Number(standingPortrait.claims_by_standing[id]) || 0;
      lines.push('  ' + STANDING_WORDS[id].label + ': ' + n + ' - moves when ' + STANDING_WORDS[id].moves_when);
    });
    lines.push('  ' + HELD_WORDS.label + ': ' + (Number(standingPortrait.held) || 0) + ' - moves when ' + HELD_WORDS.moves_when);
  }
  lines.push('A count is not a verdict. Only a person confirms a claim.');
  return lines;
}

function renderClaimViewLines(claim) {
  const lines = [];
  lines.push('Claim: ' + claim.text);
  lines.push('Claim id: ' + claim.claim_id);
  lines.push('Confirmation status: ' + claim.confirmation.review_status + ' - ' + claim.confirmation.note);
  if (typeof claim.standing === 'string' && Object.prototype.hasOwnProperty.call(STANDING_WORDS, claim.standing)) {
    lines.push('Checked against: ' + STANDING_WORDS[claim.standing].label + '. It moves when ' + STANDING_WORDS[claim.standing].moves_when + '.');
  }
  lines.push('Checking record: ' + claim.checking_record.status + ' - ' + claim.checking_record.status_note);
  const records = claim.checking_record.records || [];
  if (records.length === 0) {
    lines.push('  (no checks recorded yet)');
  } else {
    records.forEach((r, i) => {
      lines.push('  ' + (i + 1) + '. checked against: ' + r.against_id + ' (' + r.against_kind + ')');
      lines.push('     ' + r.rung_display + ' | method: ' + r.method + ' | result: ' + r.result);
      let byLine = '     by: ' + r.checked_by;
      if (r.checked_by_id) byLine += ' (' + r.checked_by_id + ')';
      byLine += ' | when: ' + r.checked_at;
      lines.push(byLine);
      if (r.note_handle) lines.push('     note: ' + r.note_handle);
      if (r.resolves_dispute === true) lines.push('     a person marked the earlier contradiction answered');
    });
  }
  return lines;
}

function renderClaimListLines(claims) {
  if (!Array.isArray(claims) || claims.length === 0) {
    return ['  (no claims filed in this room yet)'];
  }
  return claims.map((c) => (
    '  - ' + c.claim_id + ' | checking: ' + c.checking_status +
    ' | confirmation: ' + c.review_status + ' | ' + c.text_preview +
    (typeof c.standing === 'string' && Object.prototype.hasOwnProperty.call(STANDING_WORDS, c.standing)
      ? ' | ' + STANDING_WORDS[c.standing].label : '')
  ));
}

module.exports = {
  CHECK_STATUSES,
  AGAINST_KINDS,
  METHODS,
  RESULTS,
  VERIFICATION_RUNGS,
  rungInfo,
  STANDING_IDS,
  STANDING_WORDS,
  HELD_WORDS,
  PROVENANCE_EDGE_TYPES,
  FLOOR_IDS,
  FLOOR_ALIASES,
  DEFAULT_FLOOR_ID,
  FLOOR_WORDS,
  claimStanding,
  READINESS_CLAIM_TYPES,
  readReadinessCounts,
  standingMeetsFloor,
  deriveCheckStatus,
  recordClaimVerification,
  readClaimVerification,
  listClaimsForChecking,
  readVerificationPortrait,
  readStandingPortrait,
  renderPortraitLines,
  renderClaimViewLines,
  renderClaimListLines,
};
