'use strict';

// B1: local verification records for claim nodes.
//
// A verification record answers "what was this claim checked against?" It is
// evidence of a checking action, not a truth promotion. Claims remain at their
// existing review_status until a human gate promotes them.
//
// Phase 358-01 (Rome B1): adds the ONE ordered rung constant, rung and
// checked_by_id on the record, the sticky "disputed" rule, a claim-view
// reader, a claims-list reader, a room portrait broken out by rung, and the
// plain-text render helpers the CLI (358-03) and the MCP tools (358-04) both
// print. This file is the only write door (writeClaimProperties -> insertNode)
// and the only place the rung labels are written (Canon Part 9, Part 8).
//
// NO em-dashes in this file (CLAUDE.md HARD RULE); hyphens only.

const { insertNode } = require('../node-insert.cjs');

const CHECK_STATUSES = Object.freeze(new Set([
  'unchecked', 'checked', 'disputed', 'inconclusive',
]));
const AGAINST_KINDS = Object.freeze(new Set([
  'artifact', 'source', 'observation', 'person', 'experiment',
]));
const METHODS = Object.freeze(new Set(['read', 'compare', 'observe', 'test', 'ask']));
const RESULTS = Object.freeze(new Set(['supports', 'contradicts', 'inconclusive']));
const ACTORS = Object.freeze(new Set(['user', 'system']));

// TODO(358): replace with the paper author's verification hierarchy from The Orientation Problem.
// Provisional source: what-ai-cannot-know.vercel.app Part V practice 3. Rung 1 is lowest; rung number = index + 1.
// NOT the problem-type rung vocabulary (lib/core/strategy/rung-vocabulary.cjs); never mix or import the two.
const VERIFICATION_RUNGS = Object.freeze([
  Object.freeze({ id: 'own_intuition', label: 'Your own intuition' }),
  Object.freeze({ id: 'model_counter_argument', label: 'A counter-argument generated by the model' }),
  Object.freeze({ id: 'database_or_document', label: 'A database or a document' }),
  Object.freeze({ id: 'primary_source', label: 'A primary source' }),
  Object.freeze({ id: 'dissenting_person', label: 'A person who disagrees with you' }),
]);

// rungInfo(n) -- 1-based; null when n is not an integer 1..VERIFICATION_RUNGS.length.
function rungInfo(n) {
  if (!Number.isInteger(n) || n < 1 || n > VERIFICATION_RUNGS.length) return null;
  const entry = VERIFICATION_RUNGS[n - 1];
  return { rung: n, id: entry.id, label: entry.label };
}

// STATUS_NOTES / CONFIRMATION_NOTES -- the ONE place these labels are written,
// so the CLI and Desktop always show the same words, and "checked" can never
// be read as "confirmed" (Separation from approval, Canon Part 12).
const STATUS_NOTES = Object.freeze({
  unchecked: 'no checking record yet',
  checked: 'checked is not the same as confirmed',
  disputed: 'at least one check contradicts this claim; it stays disputed until a person marks the contradiction answered',
  inconclusive: 'the latest check was inconclusive',
});
const CONFIRMATION_NOTES = Object.freeze({
  proposed: 'Proposed. Only a person can confirm this claim. A checking record never confirms it.',
  confirmed: 'Confirmed by a person.',
});
function confirmationNote(reviewStatus) {
  return Object.prototype.hasOwnProperty.call(CONFIRMATION_NOTES, reviewStatus)
    ? CONFIRMATION_NOTES[reviewStatus]
    : 'Only a person changes this status. A checking record never does.';
}

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function cleanString(value, max) {
  if (typeof value !== 'string' || value.length === 0 || value.length > max) return '';
  return value;
}

function readNode(db, claimId) {
  try {
    return db.prepare('SELECT id, type, properties, review_status FROM nodes WHERE id = ?').get(claimId);
  } catch (_e) {
    return null;
  }
}

function parseProperties(row) {
  try {
    const parsed = JSON.parse(row && row.properties ? row.properties : '{}');
    return isPlainObject(parsed) ? parsed : {};
  } catch (_e) {
    return {};
  }
}

function writeClaimProperties(db, row, properties) {
  const parsed = JSON.stringify(properties);
  try {
    insertNode(db, row.id, row.type, parsed, {
      source_path: 'verification:' + row.id,
      created_by: 'system',
      epistemic_type: typeof properties.epistemic_type === 'string'
        ? properties.epistemic_type : 'extracted_fact',
    });
    return { ok: true };
  } catch (e) {
    return { ok: false, reason: 'verification_write_failed', detail: String(e.message || '').slice(0, 100) };
  }
}

// normalizeRecords(records) -- keeps only plain objects whose result is a
// member of the closed RESULTS enum. Malformed stored entries are ignored by
// every reader so a corrupted row degrades gracefully instead of throwing.
function normalizeRecords(records) {
  if (!Array.isArray(records)) return [];
  return records.filter((r) => isPlainObject(r) && RESULTS.has(r.result));
}

// deriveCheckStatus(records) -- the ONLY place check status is computed. A
// contradicts record disputes the claim UNTIL a later record carries
// resolves_dispute:true with checked_by:'user' (the "Disputed sticks" /
// "Who checked" navigator rulings, 2026-09-23). A plain (non-resolving)
// supports after a contradicts never clears the dispute.
function deriveCheckStatus(records) {
  const normalized = normalizeRecords(records);
  if (normalized.length === 0) return 'unchecked';
  let lastResolveIndex = -1;
  for (let i = 0; i < normalized.length; i += 1) {
    if (normalized[i].resolves_dispute === true && normalized[i].checked_by === 'user') {
      lastResolveIndex = i;
    }
  }
  for (let i = lastResolveIndex + 1; i < normalized.length; i += 1) {
    if (normalized[i].result === 'contradicts') return 'disputed';
  }
  const last = normalized[normalized.length - 1];
  return last.result === 'inconclusive' ? 'inconclusive' : 'checked';
}

/**
 * Append one checking event to a claim's additive properties JSON.
 * Required fields are generic handles or closed enums. Free-form notes are
 * represented by note_handle, so claim prose never becomes graph metadata.
 * rung, checked_by_id and resolves_dispute are all optional and additive;
 * legacy callers with none of the three keep working unchanged.
 */
function recordClaimVerification(db, params) {
  if (!isPlainObject(params)) return { ok: false, reason: 'invalid_params' };
  const claimId = cleanString(params.claim_id, 512);
  const againstId = cleanString(params.against_id, 512);
  const againstKind = cleanString(params.against_kind, 32);
  const method = cleanString(params.method, 32);
  const result = cleanString(params.result, 32);
  const checkedBy = cleanString(params.checked_by || 'user', 16);
  if (!claimId || !againstId) return { ok: false, reason: 'missing_handle' };
  if (!AGAINST_KINDS.has(againstKind)) return { ok: false, reason: 'invalid_against_kind' };
  if (!METHODS.has(method)) return { ok: false, reason: 'invalid_method' };
  if (!RESULTS.has(result)) return { ok: false, reason: 'invalid_result' };
  if (!ACTORS.has(checkedBy)) return { ok: false, reason: 'invalid_checked_by' };

  let rungRec = null;
  if (params.rung !== undefined && params.rung !== null) {
    rungRec = rungInfo(params.rung);
    if (!rungRec) return { ok: false, reason: 'invalid_rung' };
  }

  let checkedById = '';
  if (params.checked_by_id !== undefined && params.checked_by_id !== null && params.checked_by_id !== '') {
    checkedById = cleanString(params.checked_by_id, 128);
    if (!checkedById) return { ok: false, reason: 'invalid_checked_by_id' };
  }

  let resolvesDispute = false;
  if (params.resolves_dispute !== undefined) {
    if (typeof params.resolves_dispute !== 'boolean') return { ok: false, reason: 'invalid_resolves_dispute' };
    resolvesDispute = params.resolves_dispute;
    if (resolvesDispute) {
      if (checkedBy !== 'user') return { ok: false, reason: 'resolution_requires_person' };
      if (result === 'contradicts') return { ok: false, reason: 'invalid_resolution' };
    }
  }

  // CR-01: node:sqlite's DatabaseSync has no nested-transaction support (same
  // ownership idiom as lib/core/navigation/ranker-weights.cjs). A caller who
  // already opened a transaction on this handle owns COMMIT/ROLLBACK; this
  // function only opens/closes ITS OWN transaction when none is already open,
  // so a lost update under concurrent checks (T-358-04, Cowork) never happens
  // and a caller's unrelated pending writes are never discarded here.
  const owns = db.isTransaction !== true;
  if (owns) db.exec('BEGIN IMMEDIATE');
  try {
    const row = readNode(db, claimId);
    if (!row || row.type !== 'claim') {
      if (owns) db.exec('ROLLBACK');
      return { ok: false, reason: 'claim_not_found' };
    }
    const props = parseProperties(row);
    const verification = isPlainObject(props.verification) ? props.verification : {};
    const records = Array.isArray(verification.records) ? verification.records.slice() : [];

    if (resolvesDispute && deriveCheckStatus(records) !== 'disputed') {
      if (owns) db.exec('ROLLBACK');
      return { ok: false, reason: 'no_dispute_to_resolve' };
    }

    const checkedAt = cleanString(params.checked_at, 64) || new Date().toISOString();
    const record = {
      against_id: againstId,
      against_kind: againstKind,
      method: method,
      result: result,
      checked_by: checkedBy,
      checked_at: checkedAt,
    };
    const noteHandle = cleanString(params.note_handle, 512);
    if (noteHandle) record.note_handle = noteHandle;
    if (rungRec) {
      record.rung = params.rung;
      record.rung_label = rungRec.label;
    }
    if (checkedById) record.checked_by_id = checkedById;
    if (resolvesDispute) record.resolves_dispute = true;

    records.push(record);
    props.verification = { status: deriveCheckStatus(records), records: records };

    const write = writeClaimProperties(db, row, props);
    if (!write.ok) {
      if (owns) db.exec('ROLLBACK');
      return write;
    }
    if (owns) db.exec('COMMIT');
    return { ok: true, claim_id: claimId, review_status: row.review_status, verification: props.verification };
  } catch (e) {
    if (owns) db.exec('ROLLBACK');
    throw e;
  }
}

/**
 * readClaimVerification(db, claimId) -- the claim view. Confirmation
 * (review_status) and the checking record are returned side by side, labeled
 * so "checked" is never read as "confirmed" (AT2, AT4).
 */
function readClaimVerification(db, claimId) {
  const row = readNode(db, claimId);
  if (!row || row.type !== 'claim') return { ok: false, reason: 'claim_not_found' };
  const props = parseProperties(row);
  const verification = isPlainObject(props.verification) ? props.verification : {};
  const storedRecords = Array.isArray(verification.records) ? verification.records : [];
  const status = deriveCheckStatus(storedRecords);
  const records = storedRecords.filter(isPlainObject).map((r) => {
    const copy = Object.assign({}, r);
    let display = 'rung unknown';
    if (Number.isInteger(copy.rung) && copy.rung >= 1) {
      const info = rungInfo(copy.rung);
      const label = typeof copy.rung_label === 'string' && copy.rung_label.length > 0
        ? copy.rung_label
        : (info ? info.label : 'label not on file');
      display = 'rung ' + copy.rung + ' (' + label + ')';
    }
    copy.rung_display = display;
    return copy;
  });
  return {
    ok: true,
    claim: {
      claim_id: row.id,
      text: typeof props.text === 'string' ? props.text : '',
      knowledge_type: typeof props.knowledge_type === 'string' ? props.knowledge_type : '',
      confirmation: {
        review_status: row.review_status,
        note: confirmationNote(row.review_status),
      },
      checking_record: {
        status: status,
        status_note: STATUS_NOTES[status],
        records_total: records.length,
        records: records,
      },
    },
  };
}

/**
 * listClaimsForChecking(db, {query, limit}) -- a search-by-text list so an
 * officer in a new session can reopen a claim without knowing its id
 * (Pitfall 3). Newest first, case-insensitive substring match.
 */
function listClaimsForChecking(db, opts) {
  const options = isPlainObject(opts) ? opts : {};
  let query = typeof options.query === 'string' ? options.query.trim().toLowerCase() : '';
  if (query.length > 200) query = query.slice(0, 200);
  let limit = Number.isInteger(options.limit) ? options.limit : 20;
  if (limit < 1) limit = 1;
  if (limit > 100) limit = 100;

  let rows;
  try {
    rows = db.prepare("SELECT id, properties, review_status FROM nodes WHERE type = 'claim' ORDER BY rowid DESC").all();
  } catch (_e) {
    return { ok: true, total_matched: 0, claims: [] };
  }

  const kept = [];
  for (const row of rows || []) {
    const props = parseProperties(row);
    const text = typeof props.text === 'string' ? props.text : '';
    if (query && !text.toLowerCase().includes(query) && !String(row.id).toLowerCase().includes(query)) continue;
    kept.push({ row: row, props: props, text: text });
  }
  const totalMatched = kept.length;
  const claims = kept.slice(0, limit).map((entry) => {
    const verification = isPlainObject(entry.props.verification) ? entry.props.verification : {};
    const records = Array.isArray(verification.records) ? verification.records : [];
    const preview = entry.text.length <= 120 ? entry.text : entry.text.slice(0, 117) + '...';
    return {
      claim_id: entry.row.id,
      text_preview: preview,
      review_status: entry.row.review_status,
      checking_status: deriveCheckStatus(records),
      records_total: records.length,
    };
  });
  return { ok: true, total_matched: totalMatched, claims: claims };
}

/**
 * Read the B1 room portrait. Counts are descriptive and deliberately are not
 * collapsed into a score or a truth verdict (Canon Part 12). Status is
 * ALWAYS re-derived from the stored records (never read from the legacy
 * status field), so old latest-wins data is re-read under the sticky rule.
 */
function readVerificationPortrait(db) {
  const recordsByRung = {};
  for (let i = 1; i <= VERIFICATION_RUNGS.length; i += 1) recordsByRung[String(i)] = 0;
  recordsByRung.unknown = 0;

  const out = {
    claims_total: 0,
    claims_unchecked: 0,
    claims_checked: 0,
    claims_disputed: 0,
    claims_inconclusive: 0,
    records_total: 0,
    records_by_result: { supports: 0, contradicts: 0, inconclusive: 0 },
    records_by_rung: recordsByRung,
  };
  let rows;
  try {
    rows = db.prepare("SELECT properties FROM nodes WHERE type = 'claim'").all();
  } catch (_e) {
    return out;
  }
  for (const row of rows || []) {
    out.claims_total += 1;
    const props = parseProperties(row);
    const verification = isPlainObject(props.verification) ? props.verification : {};
    const storedRecords = Array.isArray(verification.records) ? verification.records : [];
    const status = deriveCheckStatus(storedRecords);
    if (status === 'unchecked') out.claims_unchecked += 1;
    if (status === 'checked') out.claims_checked += 1;
    if (status === 'disputed') out.claims_disputed += 1;
    if (status === 'inconclusive') out.claims_inconclusive += 1;
    for (const record of normalizeRecords(storedRecords)) {
      out.records_total += 1;
      if (Object.prototype.hasOwnProperty.call(out.records_by_result, record.result)) {
        out.records_by_result[record.result] += 1;
      }
      if (Number.isInteger(record.rung) && record.rung >= 1) {
        const key = String(record.rung);
        out.records_by_rung[key] = (out.records_by_rung[key] || 0) + 1;
      } else {
        out.records_by_rung.unknown += 1;
      }
    }
  }
  return out;
}

// renderPortraitLines / renderClaimViewLines / renderClaimListLines -- the
// ONE place these render strings are written; the CLI (358-03) and the MCP
// tools (358-04) both print these lines verbatim. Plain ASCII, hyphens only,
// the word "verified" never appears (Separation from approval).
function renderPortraitLines(portrait) {
  const lines = [];
  lines.push('Checking record across this room (counts only)');
  lines.push('  checked: ' + portrait.claims_checked);
  lines.push('  disputed: ' + portrait.claims_disputed);
  lines.push('  inconclusive: ' + portrait.claims_inconclusive);
  lines.push('  unchecked (no checking record yet): ' + portrait.claims_unchecked);
  lines.push('  claims in this room: ' + portrait.claims_total);
  lines.push(
    '  checks recorded: ' + portrait.records_total +
    ' (supports ' + portrait.records_by_result.supports +
    ', contradicts ' + portrait.records_by_result.contradicts +
    ', inconclusive ' + portrait.records_by_result.inconclusive + ')'
  );
  const rungKeys = Object.keys(portrait.records_by_rung || {})
    .filter((k) => k !== 'unknown')
    .sort((a, b) => Number(a) - Number(b));
  const byRungParts = rungKeys.map((k) => 'rung ' + k + ': ' + portrait.records_by_rung[k]);
  byRungParts.push('rung unknown: ' + (portrait.records_by_rung.unknown || 0));
  lines.push('  checks by rung: ' + byRungParts.join(', '));
  lines.push('A count is not a verdict. Only a person confirms a claim.');
  return lines;
}

function renderClaimViewLines(claim) {
  const lines = [];
  lines.push('Claim: ' + claim.text);
  lines.push('Claim id: ' + claim.claim_id);
  lines.push('Confirmation status: ' + claim.confirmation.review_status + ' - ' + claim.confirmation.note);
  lines.push('Checking record: ' + claim.checking_record.status + ' - ' + claim.checking_record.status_note);
  const records = claim.checking_record.records || [];
  if (records.length === 0) {
    lines.push('  (no checks recorded yet)');
  } else {
    records.forEach((r, i) => {
      lines.push('  ' + (i + 1) + '. checked against: ' + r.against_id + ' (' + r.against_kind + ')');
      lines.push('     ' + r.rung_display + ' | method: ' + r.method + ' | result: ' + r.result);
      let byLine = '     by: ' + r.checked_by;
      if (r.checked_by_id) byLine += ' (' + r.checked_by_id + ')';
      byLine += ' | when: ' + r.checked_at;
      lines.push(byLine);
      if (r.note_handle) lines.push('     note: ' + r.note_handle);
      if (r.resolves_dispute === true) lines.push('     a person marked the earlier contradiction answered');
    });
  }
  return lines;
}

function renderClaimListLines(claims) {
  if (!Array.isArray(claims) || claims.length === 0) {
    return ['  (no claims filed in this room yet)'];
  }
  return claims.map((c) => (
    '  - ' + c.claim_id + ' | checking: ' + c.checking_status +
    ' | confirmation: ' + c.review_status + ' | ' + c.text_preview
  ));
}

module.exports = {
  CHECK_STATUSES,
  AGAINST_KINDS,
  METHODS,
  RESULTS,
  VERIFICATION_RUNGS,
  rungInfo,
  deriveCheckStatus,
  recordClaimVerification,
  readClaimVerification,
  listClaimsForChecking,
  readVerificationPortrait,
  renderPortraitLines,
  renderClaimViewLines,
  renderClaimListLines,
};
