// Plan 02: the copy deck. The only place a user-visible word lives (navigator rule 2026-10-06; WS-02).
// One entry per row of UI-SPEC section 9 (369.26-UI-SPEC.md), copied character for character. The retired
// ids B31, B81, D20, D21 and D22 are absent and are never reused. B67 is the joiner: a middle dot with one
// space each side (written as an escape so this source stays ASCII). P63 names its placeholder {state}: the
// spec writes it as prose and the value is one of B40, B41, B42 or B43. tests/test-369.26-copy.cjs holds
// this file to the spec; call sites use text() from ./text and never hold a literal string.
export const COPY = {
  // Band strings (UI-SPEC 9.2)
  'B01': 'M:OS',
  'B02': 'M:OS, your data room at a glance',
  'B10': "You're in: {folder}",
  'B11': "You're in: {room}",
  'B12': "You're not in a data room yet",
  'B13': 'Last data room used: {room}',
  'B14': "Can't tell where you are right now",
  'B16': '{folder}',
  'B20': 'This folder is for: {purpose}',
  'B21': 'No purpose written yet',
  'B22': 'This folder has no description yet',
  'B23': "Can't read this folder's purpose right now",
  'B30': 'Next: {step}',
  'B32': 'Next: not recorded yet',
  'B33': "Next: can't read this right now",
  'B34': 'Next: looking it up',
  'B40': 'Room is in good shape',
  'B41': 'Room needs a checkup',
  'B42': 'Room is broken',
  'B43': "Can't check the room right now",
  'B44': 'Run a checkup',
  'B50': 'Context used: {n}%',
  'B51': 'Context used: {n}%',
  'B52': 'Context used: {n}%. Save your thinking now.',
  'B53': "Can't read context use right now",
  'B54': 'Context used: not known yet',
  'B55': 'Save my thinking',
  'B60': 'A decision is waiting',
  'B61': 'Nothing is waiting on you',
  'B62': "Can't check decisions right now",
  'B63': '{n} decisions are waiting',
  'B64': '{n} decision waiting',
  'B65': '{n} decisions waiting',
  'B66': 'Nothing waiting',
  'B67': ' \u00B7 ',
  'B68': '{n} waiting',
  'B70': 'Larry is working',
  'B80': 'Open workspace',
  'B82': 'Get help',
  'B83': 'Problem:',

  // Pane strings (UI-SPEC 9.3)
  'P00': 'Mindrian workspace',
  'P01': 'Room',
  'P02': 'Think',
  'P03': 'Sources',
  'P04': 'Review',
  'P05': 'Larry is working',
  'P10': "You're in: {room} > {folder}",
  'P11': "You're in: {room}",
  'P12': "You're not in a data room yet. Tell Larry which one to open.",
  'P20': 'What this folder is for',
  'P30': 'What to do next',
  'P31': 'Why: {reason}',
  'P32': 'No reason recorded yet',
  'P33': 'Add this step to my prompt',
  'P34': 'Added to your prompt box. Press Enter when you are ready.',
  'P35': "Couldn't add it to your prompt box right now. Try again in a moment.",
  'P40': 'Waiting on you',
  'P41': 'Nothing is waiting on you.',
  'P42': 'A decision is waiting for you.',
  'P43': 'Look at this decision',
  'P44': '{n} decisions are waiting for you.',
  'P50': 'Show details',
  'P51': 'Hide details',
  'P52': 'More things to do here',
  'P53': 'Fewer things to do',
  'P55': 'What just changed',
  'P56': 'What is still open',
  'P60': 'What this folder reads',
  'P61': 'What this folder writes',
  'P62': 'How Larry picked this step',
  'P63': 'Room health: {state}',
  'P64': 'Last updated: {time}',
  'P65': 'Version: {version}',
  'P66': 'Files behind this',
  'P70': 'What we think so far',
  'P72': 'Based on {n} pieces of evidence',
  'P73': 'Look at the evidence',
  'P74': "What we're unsure about",
  'P75': 'No evidence yet for these points',
  'P76': 'and {n} more',
  'P77': 'None found in what we read',
  'P78': 'Looking for evidence',
  'P79': 'This is the one gap that could change your decision.',
  'P80': 'Want help with this?',
  'P81': 'Dig into this',
  'P82': 'Connect to other work',
  'P83': 'Look at it another way',
  'P84': 'Why this matters',
  'P85': 'Show me an example',
  'P86': 'See the assumption underneath a point and what would test it.',
  'P87': 'See how two pieces of your work might serve the same purpose.',
  'P88': 'See a comparison or another explanation, and where it stops working.',
  'P89': 'See the reason behind the suggested step.',
  'P90': 'See a worked example.',
  'P91': 'Larry has nothing recorded for this yet.',
  'P92': 'Talk this through with Larry',
  'P93': 'Look up general guidance',
  'P94': 'Sends only the name of the method. Nothing from your data room leaves your machine.',
  'P95': 'General guidance',
  'P96': "Couldn't look that up right now. Nothing was sent from your data room.",
  'P97': 'Pick two pieces of work first.',
  // Three-digit pane ids (UI-SPEC 9.3, P100 to P124): Sources, Review and the Room action list.
  'P100': 'Sources',
  'P102': 'From {where}',
  'P103': 'Read this',
  'P104': 'No sources yet. As you add evidence to this data room, it shows up here.',
  'P105': 'Reading',
  'P106': 'Back to the list',
  'P107': 'Only the first part is shown. Open the file to read all of it.',
  'P110': 'A decision is waiting for you',
  'P111': 'Nothing is waiting on you.',
  'P112': "Can't check decisions right now.",
  'P113': 'Open until {time}',
  'P114': 'This was raised in another conversation.',
  'P115': 'Ask it here',
  'P116': '{n} decisions are waiting for you',
  'P117': 'Also waiting',
  'P120': 'Show steps for:',
  'P121': 'All folders',
  'P122': 'Add to my prompt',
  'P123': 'More things to do here',
  'P124': 'Command: {name}',

  // Card strings (UI-SPEC 9.4)
  'D01': 'Mindrian suggests:',
  'D02': 'Other choices',
  'D03': 'because {reason}',
  'D04': 'No reason recorded for this suggestion.',
  'D05': 'Choose one:',
  'D10': 'Pressing {key} saves your decision to your data room.',
  'D11': 'Pressing {key} leaves this open. Nothing is decided yet.',
  'D12': 'Pressing {key} saves your answer to your data room.',
  'D13': 'Noted. This decision stays open.',
  'D14': 'Nothing was saved. This decision is still waiting for you.',
  'D16': 'Decide later',
  'D23': 'Saving your decision',
  'D24': 'Saved to your data room: {label}.',
  'D26': 'Already saved. Nothing changed.',
  'D27': 'This was answered somewhere else. Nothing changed here.',
  'D30': 'This card lets you pick more than one answer. Answer it in the conversation.',
  'D31': 'Checking where this stands',
  'D32': 'Still current. Nothing has changed since this was drawn.',
  'D33': 'The work behind this changed after the card was drawn. Look again before you decide.',
  'D34': "Couldn't check. Look again before you decide.",

  // Marks, hints, explain, prompts (UI-SPEC 9.5)
  'L01': 'Building',
  'L02': 'Challenging',
  'L03': 'Another view',
  'L04': 'A decision',
  'L05': 'Handing over',
  'H01': 'Do this step',
  'H02': 'Look at the decision',
  'H03': 'More things to do',
  'H04': 'Show details',
  'H05': 'Help',
  'H06': 'Close',
  'H07': 'Back to the list',
  'H08': 'Dig in',
  'H09': 'Connect',
  'H10': 'Another way',
  'H11': 'Why',
  'H12': 'Example',
  'H13': 'Look up guidance',
  'H14': 'Talk it through',
  'H15': 'Choose an answer',
  'H16': 'Decide later',
  'H17': 'Look at the evidence',
  'H18': 'Explain this',
  'H19': 'Ask it here',
  'H20': 'All keys',
  'H21': 'Moving around',
  'H22': 'Tab moves to the next button. Enter presses it. Esc closes the workspace.',
  'X01': 'This tab shows where you are, what this folder is for and the next step. Nothing here changes your data room.',
  'X02': 'This tab shows what we think so far and where the evidence is thin. The help buttons show an explanation or add a question to your prompt box.',
  'X03': 'This tab lists where your evidence comes from. Pick one to read it.',
  'X04': 'This tab holds decisions waiting on you. Pressing a number saves that choice to your data room. Decide later saves nothing.',
  'Q01': 'What is the best next step in this folder, and why?',
  'Q02': 'Help me dig into the assumption under this point: {point}',
  'Q03': 'Help me connect {a} and {b}: how could they serve the same purpose?',
  'Q04': 'Show me another way to look at this point: {point}',
  'Q05': 'Talk me through this point: {point}',
  'Q06': 'Check this data room and tell me what needs fixing.',
  'Q07': 'Save what we have worked out in this conversation to my data room.',

  // Missing facts (UI-SPEC 9.5)
  'M01': 'no description yet',
  'M02': 'no purpose written yet',
  'M03': "can't read this right now",
  'M04': 'not recorded yet',

  // Notes (UI-SPEC 9.5)
  'N01': 'Colors are off. Everything is shown as words and outlines.',
  'N03': "Colors can't load. Showing plain text.",
  'N04': 'Sample data. This is not a real data room.',
  'N05': 'This window is narrow. Make it wider to read the workspace comfortably.',
  'N06': 'Press o to use the workspace keys.',

  // Refusals and errors (UI-SPEC 9.5)
  'E01': 'This decision card is not one this window drew. Ask for it again.',
  'E02': 'This decision card ran out of time. Ask for it again.',
  'E03': 'The work behind this decision changed. Look at the evidence again, then decide on a fresh card.',
  'E04': 'This decision was raised in another conversation. Ask it here to answer it.',
  'E05': 'That choice is not on this card. Pick one of the listed choices.',
  'E06': "Can't reach your data room right now. Nothing was saved.",
  'E07': 'That did not work. Nothing was changed. Try again in a moment.',
} as const

export type CopyId = keyof typeof COPY
