#!/usr/bin/env bash
# Phase 205 aggregator (larry-loop-elevation). Grows as 205 builds.
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
echo "== 205: elevation-doctrine consistency floor =="
node "$DIR/test-205-elevation-doctrine-floor.cjs"
echo "== 205-02: Frame node + SHARES_JOB / ELEVATES_TO edges (D-Q5) =="
node "$DIR/test-205-frame-node.cjs"
echo "== 205-02: edge allow-list additive drift floor =="
node "$DIR/test-edges-part4-cascade-floor.cjs"
echo "== 205-06: pipelining (SENS-10 exits compose; runChain safe-halt) =="
node "$DIR/test-205-pipelining.cjs"
echo "== 205-04: elevation companion axis alongside the gears (item 8) =="
node "$DIR/test-205-elevation-axis.cjs"
echo "== 205-04: frozen-six drift guard - GRILL/REFRAME/FUSION mint no reach (item 7) =="
node "$DIR/test-205-frozen-six-guard.cjs"
echo "== 205-05: two orthogonal decision axes + role_level + NO-CUTE-IRONY (items 4/5) =="
node "$DIR/test-205-decision-axes.cjs"
echo "== 205-05: frozen-scalar floor (0.70 detent reused, mints nothing) =="
node "$DIR/test-canon-frozen-scalars-floor.cjs"
echo "ALL 205 TESTS PASS"
