#!/usr/bin/env bash
# Phase 240.1 verification aggregator: the single PASS/FAIL gate for
# "context-layer drift detection" (CTXL-01 state-version stamp preservation,
# CTXL-02 semantic-layer vs context-layer doctrine, CTXL-03 room-context
# accuracy benchmark).
#
# (1) DISCOVERY IS BY GLOB, NOT BY LIST. This harness globs every
# tests/test-240.1-* file (both .cjs and .sh) and runs it. Adding a Phase
# 240.1 test requires NO edit to this runner. There is deliberately no
# hand-maintained execution list anywhere below: a list is a second place to
# forget something.
#
# Filename discipline, stated here in the runner's own words: the aggregator
# filename strips the dot (run-all-2401.sh, matching the existing
# tests/run-all-1432.sh and tests/run-all-1441.sh), while the TEST filenames
# keep it (tests/test-240.1-*.cjs). The globs below are therefore
# tests/test-240.1-*.cjs and tests/test-240.1-*.sh.
#
# (2) THE SIX MANDATORY TEST FILENAMES, enumerated by name so a missing one
# is visible by READING this header even though the glob does the actual
# discovery. Each is tagged with the requirement it proves and the plan that
# lands it:
#
#   test-240.1-state-version-preserved.cjs      CTXL-01   plan 240.1-02
#   test-240.1-state-version-drift-gate.cjs     CTXL-01   plan 240.1-02
#   test-240.1-hook-write-site.sh               CTXL-01   plan 240.1-03
#   test-240.1-layer-doctrine-presence.cjs      CTXL-02   plan 240.1-04
#   test-240.1-ctxl-fixture.cjs                 CTXL-03   plan 240.1-05
#   test-240.1-ctxl-eval-gate.cjs               CTXL-03   plan 240.1-06
#
# A test named above that is missing from disk is NOT reported by this runner
# as a failure, because a file that does not exist cannot be globbed. That is
# the honest limitation of glob discovery and the reason the names are
# written out here: the header is the checklist, the glob is the executor.
# What the runner DOES catch, loudly, is the case where NOTHING at all is
# discovered.
#
# Until the first tests/test-240.1-* file lands, this harness legitimately
# exits 1 with the message below -- that is the guard working exactly as
# designed, not a defect in this file.
#
# (3) THE found-eq-0 GUARD IS LOAD-BEARING AND MUST NOT BE SOFTENED. A
# harness that discovers nothing must FAIL, not print green. A clean summary
# over an empty discovery is the same false-success shape this milestone
# exists to close.
#
# run_may_skip is REQUIRED for Phase 240.1 (this phase ships
# tests/test-240.1-hook-write-site.sh, a bash leg that may legitimately
# self-SKIP on environment). An environment self-skip is tallied as SKIP,
# never as a pass it did not earn.
#
# GLOB-DISCIPLINE SELF-TEST (plan 240.1-01 Task 1). There are already four
# tests/test-240-* files on disk from Phase 240; a sloppy glob would silently
# re-run Phase 240's suite and report it as 240.1 coverage. This leg proves,
# in a scratch mktemp -d directory, that the tests/test-240.1-* pattern does
# NOT expand to a bare tests/test-240-* decoy and DOES expand to a genuine
# tests/test-240.1-* decoy, then asserts every REAL discovered basename
# begins with the literal test-240.1-.
#
# SCOPE-ESCAPE TRIPWIRE (plan 240.1-01 Task 2, appended after this Task 1
# header). It turns locked decision D-01 (CTXL-01 targets the PER-ROOM
# STATE.md generated by scripts/compute-state, NOT .planning/STATE.md, which
# is written by gsd-core, external to this repo and already root-caused
# elsewhere with no in-repo fix available) into a standing machine check
# rather than prose in a ROADMAP.
#
# Every leg in this file is fully hermetic and makes ZERO network reach. No
# emoji. No em-dashes, no en-dashes -- hyphens only.

set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PASS=0
FAIL=0
SKIP=0
run() {
  local label="$1"; shift
  echo "--- $label ---"
  if "$@"; then echo ">>> $label: PASSED"; PASS=$((PASS+1)); else echo ">>> $label: FAILED"; FAIL=$((FAIL+1)); fi
  echo ""
}

# A leg that may legitimately self-SKIP on environment. Exit 0 plus a SKIP
# line is tallied as SKIP, not as a pass it did not earn.
run_may_skip() {
  local label="$1"; shift
  local out rc
  echo "--- $label ---"
  out="$("$@" 2>&1)"; rc=$?
  printf '%s\n' "$out"
  if [ "$rc" -ne 0 ]; then
    echo ">>> $label: FAILED"; FAIL=$((FAIL+1))
  elif printf '%s' "$out" | grep -qE '^SKIP'; then
    echo ">>> $label: SKIPPED"; SKIP=$((SKIP+1))
  else
    echo ">>> $label: PASSED"; PASS=$((PASS+1))
  fi
  echo ""
}

# Strip whole-line comments (// or block-comment body lines, and # for
# python/sh) so header prose can neither trip a grep nor satisfy one.
strip_comments() {
  grep -vE '^[[:space:]]*(//|\*|/\*|#)' "$1" 2>/dev/null
}

shopt -s nullglob

# ---------------------------------------------------------------------------
# Shared scratch directory for this file's self-tests: the glob-discipline
# leg below (Task 1) and the scope-escape tripwire self-test appended by
# plan 240.1-01 Task 2. One mktemp -d, one trap, reused by both legs.
# ---------------------------------------------------------------------------
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

EMPTY_DISCOVERY=0
found=0
for t in tests/test-240.1-*.cjs; do
  found=1
  run "$(basename "$t")" node "$t"
done
for t in tests/test-240.1-*.sh; do
  found=1
  run_may_skip "$(basename "$t")" bash "$t"
done

if [ $found -eq 0 ]; then
  echo "!!! no tests/test-240.1-* files discovered"
  EMPTY_DISCOVERY=1
fi

# ---------------------------------------------------------------------------
# GLOB-DISCIPLINE SELF-TEST (plan 240.1-01 Task 1): proves the tests/test-
# 240.1-* glob cannot mistake Phase 240's existing suite for Phase 240.1
# coverage.
# ---------------------------------------------------------------------------
echo "--- glob-discipline self-test: the 240.1 glob cannot mistake Phase 240 for Phase 240.1 ---"
GLOB_SELFTEST_OK=1
mkdir -p "$TMP/glob-probe"
echo "// decoy: this is Phase 240, not 240.1" > "$TMP/glob-probe/test-240-decoy.cjs"
echo "// decoy: this is genuinely Phase 240.1" > "$TMP/glob-probe/test-240.1-decoy.cjs"

MUST_NOT_MATCH_HIT=0
for t in "$TMP"/glob-probe/test-240.1-*.cjs; do
  [ "$(basename "$t")" = "test-240-decoy.cjs" ] && MUST_NOT_MATCH_HIT=1
done
if [ "$MUST_NOT_MATCH_HIT" -eq 0 ]; then
  echo "    correctly excluded (must_not_match): test-240-decoy.cjs"
else
  echo "    FALSE POSITIVE (must_not_match): the 240.1 glob matched test-240-decoy.cjs"
  GLOB_SELFTEST_OK=0
fi

MUST_MATCH_HIT=0
for t in "$TMP"/glob-probe/test-240.1-*.cjs; do
  [ "$(basename "$t")" = "test-240.1-decoy.cjs" ] && MUST_MATCH_HIT=1
done
if [ "$MUST_MATCH_HIT" -eq 1 ]; then
  echo "    correctly matched (must_match): test-240.1-decoy.cjs"
else
  echo "    MISS (must_match, the gate is blind to this): test-240.1-decoy.cjs"
  GLOB_SELFTEST_OK=0
fi

# Assert over the REAL discovered set that every discovered basename begins
# with the literal test-240.1-. A leg failure prints the offending basename.
for t in tests/test-240.1-*.cjs tests/test-240.1-*.sh; do
  base="$(basename "$t")"
  case "$base" in
    test-240.1-*) : ;;
    *)
      echo "    FALSE POSITIVE on the real discovered set: $base does not begin with test-240.1-"
      GLOB_SELFTEST_OK=0
      ;;
  esac
done

if [ "$GLOB_SELFTEST_OK" -eq 1 ]; then
  echo ">>> glob-discipline self-test: the 240.1 glob cannot mistake Phase 240 for Phase 240.1: PASSED"; PASS=$((PASS+1))
else
  echo ">>> glob-discipline self-test: the 240.1 glob cannot mistake Phase 240 for Phase 240.1: FAILED"; FAIL=$((FAIL+1))
fi
echo ""

shopt -u nullglob

echo "======================================"
echo "Phase 240.1: PASS=$PASS FAIL=$FAIL SKIP=$SKIP"
echo "======================================"
if [ "$EMPTY_DISCOVERY" -eq 1 ]; then
  exit 1
fi
[ "$FAIL" -eq 0 ]
