#!/usr/bin/env python3
"""Turn navigator-APPROVED proposals into Cypher. It never connects to the database and never executes.
Usage: approve_write.py PROPOSALS.json APPROVED_IDS.txt OUT.cypher [--run-id ID]
Refuses any proposal that has no evidence with a source pointer, an unapproved id, a type outside the allow-list,
or an undetermined direction. The agent runs the output through the write tool only after the navigator says yes."""
import argparse, datetime, os, re, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "lib"))
import json
from common import SEMANTIC_TYPES


def q(s):
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ") + "'"


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("proposals"); ap.add_argument("approved"); ap.add_argument("out")
    ap.add_argument("--run-id", default=datetime.datetime.utcnow().strftime("graph-rel-%Y%m%d%H%M%S"))
    a = ap.parse_args(argv)
    props = {p["id"]: p for p in json.load(open(a.proposals, encoding="utf-8"))}
    ok = [x.strip() for x in open(a.approved, encoding="utf-8").read().split() if x.strip()]
    lines, refused = ["// Generated by approve_write.py. Run only after navigator approval. One edge per statement."], []
    for pid in ok:
        p = props.get(pid)
        if not p:
            refused.append((pid, "unknown id")); continue
        t = p.get("approved_type") or p.get("suggested_type")
        d = p.get("direction")
        ev = [e for e in p.get("evidence", []) if isinstance(e, dict) and e.get("source") and e.get("quote")]
        if t not in SEMANTIC_TYPES or not re.fullmatch(r"[A-Z_]+", t or ""):
            refused.append((pid, "type not allowed")); continue
        if d not in ("s_to_t", "t_to_s"):
            refused.append((pid, "direction undetermined")); continue
        if not ev:
            refused.append((pid, "no evidence with source and quote")); continue
        s, tt = (p["s"], p["t"]) if d == "s_to_t" else (p["t"], p["s"])
        lines.append(
            f"MATCH (a) WHERE elementId(a) = {q(s)} MATCH (b) WHERE elementId(b) = {q(tt)} "
            f"MERGE (a)-[r:{t}]->(b) ON CREATE SET r.created_at = datetime(), r.added_by = 'graph-relations-agent', "
            f"r.run_id = {q(a.run_id)}, r.status = 'navigator-approved', r.proposal_id = {q(pid)}, "
            f"r.proposed_by = {q(','.join(p.get('methods', [])))}, r.evidence = {q(ev[0]['source'] + ' :: ' + ev[0]['quote'][:300])};")
    open(a.out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"{len(lines) - 1} statements written, {len(refused)} refused -> {a.out}")
    for pid, why in refused:
        print("  refused", pid, why)
    return 0 if not refused else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
