/*
 * Copyright (c) 2026 Mindrian. BSL 1.1.
 *
 * Phase 118-04 Plan 04 Task 2 -- mva-deck-builder tests.
 *
 * The deck builder is a pure function that takes an OrchestratorOutcome
 * (from Plan 118-03) and returns a full HTML document. De Stijl theme,
 * INLINE styles only (no <style> blocks), Mondrian palette, em-dash-free.
 *
 * Canon Part 8 invariants:
 *   - The deck contains the RENDERED summary_lines + structured deck_data
 *     (already sanitized by Plan 118-02 agents).
 *   - The raw sentence is NEVER serialized into the HTML.
 *   - The sentence sha256 hash IS rendered (as a hash marker, not a leak).
 *
 * Em-dash discipline (per feedback_no_emdashes.md): every emitted string
 * uses `--` and `-` ONLY. The 3-option footer uses `--` not `—`.
 *
 * No real-name discipline (per feedback_no_real_names_in_repo.md): the
 * template MUST NOT mention testers/advisors/partners.
 *
 * Per OQ13 lean: deck includes "Generated by MindrianOS" footer with link to
 * the install minisite.
 *
 * Per OQ15 lean: deck shows static 3-option text + copy-to-clipboard button
 * for the brief sha8.
 *
 * NIT-3 palette parity: DECK_PALETTE must match the De Stijl source-of-truth
 * (lib/wiki/wiki-layout.cjs CSS variables; lib/core/visual-ops.cjs DS_HEX).
 */
'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const { buildDeck, buildSlide, DECK_PALETTE } = require('./mva-deck-builder.cjs');

// ---------- Synthetic OrchestratorOutcome factories ----------

function _agentOk(agent_id, summary_line, extra) {
  return {
    agent_id,
    status: 'ok',
    duration_ms: 100,
    payload: Object.assign({ summary_line }, extra || {}),
  };
}

function _agentEmpty(agent_id, reason) {
  return {
    agent_id,
    status: 'empty',
    duration_ms: 10,
    payload: { reason: reason || 'no_findings' },
  };
}

function _agentError(agent_id) {
  return {
    agent_id,
    status: 'error',
    duration_ms: 10,
    error: 'mock_error',
    payload: null,
  };
}

function _sixOkOutcome() {
  const sha = '0'.repeat(64);
  return {
    results: [
      _agentOk('brain_similar',       'Found 3 ventures in this space: A, B, C',
               { deck_data: { ventures: [{ name: 'A', stage: 'seed' }, { name: 'B', stage: 'pre-seed' }] } }),
      _agentOk('brain_cross_domain',  'Cross-domain analogy: ConstraintTheory -- bottleneck pattern',
               { deck_data: { framework: 'ConstraintTheory', signature: 'bottleneck pattern' } }),
      _agentOk('brain_classic_traps', 'Classic trap: PrematureScale -- raised before PMF',
               { deck_data: { trap: 'PrematureScale', signature: 'raised before PMF' } }),
      _agentOk('tavily_funding',      'Live funding match: NSF SBIR Phase I -- deadline 2026-06-15',
               { deck_data: { title: 'NSF SBIR Phase I', deadline: '2026-06-15' } }),
      _agentOk('six_hats_red_black',  "One question you haven't asked yourself: What if no one cares?",
               { deck_data: { question: 'What if no one cares?' } }),
      _agentOk('dashboard_graph',     'Your room already has 5 related decision nodes. Quick preview:',
               { deck_data: { node_count: 5, nodes: ['Idea-2026-03', 'Pivot-2026-04'] } }),
    ],
    rendered: '(stub terminal output)',
    footer_data: { ok: 6, failed: 0, sha256: sha },
  };
}

// ---------- Tests ----------

test('Test 1: 6 agents ok -> 6 slides + header + footer; valid HTML', () => {
  const outcome = _sixOkOutcome();
  const html = buildDeck(outcome);
  assert.ok(html.startsWith('<!DOCTYPE html>'), 'must start with DOCTYPE');
  assert.ok(html.endsWith('</html>\n') || html.endsWith('</html>'),
    'must end with </html>');
  // 6 slide articles
  const slideCount = (html.match(/<article\b/g) || []).length;
  assert.equal(slideCount, 6, 'expected 6 slides, got ' + slideCount);
  assert.ok(html.length > 2000, 'deck should be substantive (>2000 chars), got ' + html.length);
});

test('Test 2: em-dash sweep -- zero — characters in output', () => {
  const outcome = _sixOkOutcome();
  const html = buildDeck(outcome);
  const matches = html.match(/—/g);
  assert.equal(matches, null, 'no em-dashes (—) allowed; found ' + (matches && matches.length));
  // Verify `--` IS present in 3-option footer
  assert.ok(html.includes("Challenge me -- Devil"), 'footer must contain "Challenge me -- Devil"');
});

test('Test 3: no <style> blocks anywhere in output', () => {
  const outcome = _sixOkOutcome();
  const html = buildDeck(outcome);
  assert.equal(/<style[^>]*>/.test(html), false,
    'no <style> blocks allowed; inline styles only');
});

test('Test 4: inline styles present (>= 10 style="" attributes)', () => {
  const outcome = _sixOkOutcome();
  const html = buildDeck(outcome);
  const inlineMatches = html.match(/style="[^"]+"/g) || [];
  assert.ok(inlineMatches.length >= 10,
    'expected >= 10 inline style attributes, got ' + inlineMatches.length);
});

test('Test 5: Mondrian/De Stijl palette present (>= 3 of canonical hexes)', () => {
  const outcome = _sixOkOutcome();
  const html = buildDeck(outcome);
  const palette = Object.values(DECK_PALETTE);
  let hits = 0;
  for (const hex of palette) {
    if (html.toUpperCase().includes(hex.toUpperCase())) hits += 1;
  }
  assert.ok(hits >= 3, 'expected >= 3 palette hexes in HTML, got ' + hits);
});

test('Test 6: 3 empty agents render placeholder slides', () => {
  const sha = 'a'.repeat(64);
  const outcome = {
    results: [
      _agentOk('brain_similar', 'A B C'),
      _agentEmpty('brain_cross_domain'),
      _agentEmpty('brain_classic_traps'),
      _agentEmpty('tavily_funding', 'tavily_unavailable'),
      _agentOk('six_hats_red_black', "What if no one cares?"),
      _agentOk('dashboard_graph', 'Your room has 2 nodes.'),
    ],
    rendered: '',
    footer_data: { ok: 3, failed: 3, sha256: sha },
  };
  const html = buildDeck(outcome);
  const slideCount = (html.match(/<article\b/g) || []).length;
  assert.equal(slideCount, 6, '6 slides total (3 ok + 3 empty placeholders)');
  // Placeholder phrase appears (matches renderer empty-state strings)
  assert.ok(html.includes('no findings this pass') || html.includes('Live funding scan'),
    'empty agents should render placeholder text');
});

test('Test 7: all-fail -> single sharp-question slide', () => {
  const sha = 'b'.repeat(64);
  const outcome = {
    results: [
      _agentError('brain_similar'),
      _agentError('brain_cross_domain'),
      _agentError('brain_classic_traps'),
      _agentError('tavily_funding'),
      _agentError('six_hats_red_black'),
      _agentError('dashboard_graph'),
    ],
    rendered: '',
    footer_data: { ok: 0, failed: 6, sha256: sha },
  };
  const html = buildDeck(outcome);
  // Exactly one slide article on all-fail
  const slideCount = (html.match(/<article\b/g) || []).length;
  assert.equal(slideCount, 1, 'all-fail should render exactly 1 slide');
  // Verbatim sharp-question source-spec text (em-dash-free)
  assert.ok(html.includes("didn't find precedents for this in 30 seconds"),
    'sharp-question text must appear');
  assert.ok(html.includes('genuinely unexplored space'),
    'sharp-question second line must appear');
});

test('Test 8: raw-sentence absent -- only sha8 marker appears, no "sentence"/"prompt"/"user_input" fields', () => {
  const outcome = _sixOkOutcome();
  const html = buildDeck(outcome);
  // sha8 (first 8 chars of sha256) IS rendered as identifier
  assert.ok(html.includes(outcome.footer_data.sha256.slice(0, 8)),
    'sha8 should appear as the brief identifier');
  // But raw "sentence" / "prompt" / "user_input" field labels do NOT appear
  // (We check for the field-label patterns, not arbitrary occurrences of "sentence")
  assert.equal(/raw_sentence|MVA_SENTENCE|user_input|user_prompt/i.test(html), false,
    'no raw sentence field labels should appear in HTML');
});

test('Test 9: footer includes "Generated by MindrianOS" attribution + install-site link', () => {
  const outcome = _sixOkOutcome();
  const html = buildDeck(outcome);
  assert.ok(html.includes('Generated by MindrianOS'),
    'footer must include "Generated by MindrianOS" attribution');
  assert.ok(html.includes('mindrianos-install-site.vercel.app'),
    'footer must link to install minisite');
  assert.ok(html.includes(outcome.footer_data.sha256.slice(0, 8)),
    'footer must include sha8 marker');
});

test('Test 10: 3-option footer text + copy-to-clipboard button for /mos:new-project --from-brief <sha8>', () => {
  const outcome = _sixOkOutcome();
  const html = buildDeck(outcome);
  // 3-option verbatim text (em-dash-free)
  assert.ok(html.includes('What now?'), 'must include "What now?" prompt');
  assert.ok(html.includes("Just tell me what's new") || html.includes('Just tell me what&#39;s new'),
    'option 1 text');
  assert.ok(html.includes('Build a room around this'), 'option 2 text');
  assert.ok(html.includes("Devil's Advocate") || html.includes('Devil&#39;s Advocate'),
    "option 3 text contains Devil's Advocate");
  // Copy-to-clipboard hint
  const sha8 = outcome.footer_data.sha256.slice(0, 8);
  assert.ok(html.includes('/mos:new-project --from-brief ' + sha8),
    'copy hint must include /mos:new-project --from-brief <sha8>');
});

test('Test 11: data/mva-deck-template.html exists + has placeholder tokens', () => {
  const tmplPath = path.join(__dirname, '..', '..', 'data', 'mva-deck-template.html');
  assert.ok(fs.existsSync(tmplPath), 'template must exist at ' + tmplPath);
  const tmpl = fs.readFileSync(tmplPath, 'utf8');
  assert.ok(tmpl.includes('{{HEADER}}'), 'template must have {{HEADER}}');
  assert.ok(tmpl.includes('{{SLIDES}}'), 'template must have {{SLIDES}}');
  assert.ok(tmpl.includes('{{FOOTER}}'), 'template must have {{FOOTER}}');
});

test('Test 12: NIT-3 palette parity with lib/wiki/wiki-layout.cjs', () => {
  const wikiPath = path.join(__dirname, '..', '..', 'lib', 'wiki', 'wiki-layout.cjs');
  if (!fs.existsSync(wikiPath)) {
    // Documented skip per plan-checker iter 2 NIT-3
    console.log('  (skipped: lib/wiki/wiki-layout.cjs absent; palette is freshly defined for the MVA deck)');
    return;
  }
  const wikiSource = fs.readFileSync(wikiPath, 'utf8');
  const divergent = [];
  for (const [name, hex] of Object.entries(DECK_PALETTE)) {
    const hexUpper = hex.toUpperCase();
    const wikiHasSameHex = wikiSource.toUpperCase().includes(hexUpper);
    if (!wikiHasSameHex) {
      const wikiMentionsColor = new RegExp('\\b' + name + '\\b', 'i').test(wikiSource);
      if (wikiMentionsColor) {
        const otherHexes = (wikiSource.match(/#[0-9A-Fa-f]{6}/g) || []).map(h => h.toUpperCase());
        // Only flag if wiki has hex literals AND wiki names this color
        if (otherHexes.length > 0) {
          divergent.push(
            name + ': deck=' + hex + ', wiki references "' + name + '" but uses different hex(es): ' +
            otherHexes.slice(0, 3).join(', ')
          );
        }
      }
    }
  }
  assert.equal(divergent.length, 0,
    'Palette divergence detected vs lib/wiki/wiki-layout.cjs:\n  ' + divergent.join('\n  ') +
    '\nReconcile DECK_PALETTE with wiki-layout.cjs or document the divergence in the SUMMARY.');
});

test('Test 13: Canon Part 8 source grep -- builder source has no raw-sentence references', () => {
  const code = fs.readFileSync(path.join(__dirname, 'mva-deck-builder.cjs'), 'utf8');
  // Strip comments
  const stripped = code.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
  assert.equal(stripped.match(/MVA_SENTENCE/), null, 'no MVA_SENTENCE in builder source');
  assert.equal(stripped.match(/process\.env\.CLAUDE_USER_PROMPT/), null,
    'no process.env.CLAUDE_USER_PROMPT in builder source');
  // Template-level forbidden tokens + real-name discipline
  const tmplPath = path.join(__dirname, '..', '..', 'data', 'mva-deck-template.html');
  const template = fs.readFileSync(tmplPath, 'utf8');
  assert.equal(template.match(/MVA_SENTENCE/), null, 'no MVA_SENTENCE in template');
  // feedback_no_real_names_in_repo.md: no biographical tester/advisor names in deck template
  assert.equal(template.match(/Lawrence|Gary|Natan|Aronhime|Reuven|Schler/), null,
    'no real names in template (per feedback_no_real_names_in_repo.md)');
});

test('Test 14: buildSlide is exported and produces an <article>', () => {
  const slideHtml = buildSlide(_agentOk('brain_similar', 'Found 3 ventures: A, B, C'));
  assert.ok(slideHtml.includes('<article'), 'slide must be wrapped in <article>');
  assert.ok(slideHtml.includes('A, B, C'), 'slide must contain the summary line');
});
