'use strict';

/*
 * Phase 115-02 -- shallow-doc-parser unit tests (8 fixtures + ancillary)
 *
 * Test map (mirrors PLAN <behavior>):
 *   PR-01..PR-03  parseRoleHints  3 fixtures
 *   PV-01..PV-03  parseVentureHint  3 fixtures
 *   PC-01         parseClaims  1 fixture
 *   ES-01         extractShallow happy-path  1 integration fixture
 *   ES-02         extractShallow graceful-degradation  1 fixture
 *
 * Navigation API is STUBBED via Module._resolveFilename redirect to a
 * generated __nav-stub.cjs that records calls into navStub.__calls. This
 * keeps the unit test free of room.db side effects; live integration is
 * covered by tests/test-115-dual-path-integration.sh (Task 4).
 *
 * Canon Part 7 alignment: stub mirrors the (sessionId, nodeId, setBy)
 * surface the parser writes through. The parser MUST NOT require
 * room-db.cjs directly; that contract is enforced by a grep in <verify>.
 */

const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const Module = require('node:module');

// ---------- Generate the navigation stub ----------

const stubPath = path.resolve(__dirname, '__nav-stub.cjs');
const navStubSource = `'use strict';
// Auto-generated by shallow-doc-parser.test.cjs. DO NOT edit by hand; the
// surface is defined to mirror lib/core/navigation.cjs as Phase 115-02
// expects to consume it (sessionId/nodeId/setBy form for setFocus,
// sessionId/eventType/payload form for recordMemoryEvent).
const calls = { setFocus: [], memoryEvents: [], getActiveFocus: [] };
function reset() { calls.setFocus.length = 0; calls.memoryEvents.length = 0; calls.getActiveFocus.length = 0; }
module.exports = {
  setFocus: function (sid, nid, sb) { calls.setFocus.push({ sid: sid, nid: nid, sb: sb }); return { ok: true, eventId: 'stub-evt-' + calls.setFocus.length }; },
  recordMemoryEvent: function (sid, type, payload) { calls.memoryEvents.push({ sid: sid, type: type, payload: payload }); return { ok: true, eventId: 'stub-mem-' + calls.memoryEvents.length }; },
  getActiveFocus: function (sid) { calls.getActiveFocus.push({ sid: sid }); return null; },
  __calls: calls,
  __reset: reset,
};
`;
fs.writeFileSync(stubPath, navStubSource);

// ---------- Redirect ./navigation.cjs requires from inside lib/core/ ----------

const targetParserPath = path.resolve(__dirname, 'shallow-doc-parser.cjs');
const originalResolve = Module._resolveFilename;
Module._resolveFilename = function (request, parent, ...rest) {
  if (request === './navigation.cjs' && parent && parent.filename === targetParserPath) {
    return stubPath;
  }
  return originalResolve.call(this, request, parent, ...rest);
};

// ---------- Test scaffolding ----------

let passed = 0;
let failed = 0;
function run(name, fn) {
  try {
    fn();
    process.stdout.write('ok  ' + name + '\n');
    passed += 1;
  } catch (err) {
    process.stderr.write('FAIL ' + name + '\n' + (err && err.stack ? err.stack : String(err)) + '\n');
    failed += 1;
  }
}

const { extractShallow, parseRoleHints, parseVentureHint, parseClaims } = require(targetParserPath);
const navStub = require(stubPath);

// ---------- parseRoleHints (3 fixtures) ----------

run('PR-01 Founder of Acme Robotics -> Founder', () => {
  const r = parseRoleHints('Founder of Acme Robotics');
  assert.ok(r, 'parseRoleHints returned null');
  assert.equal(r.canonical_role, 'Founder');
  assert.equal(typeof r.confidence, 'number');
  assert.ok(r.confidence > 0 && r.confidence <= 1);
});

run('PR-02 PhD Researcher in cancer biology, NIH-funded -> Researcher', () => {
  const r = parseRoleHints('PhD Researcher in cancer biology, NIH-funded');
  assert.ok(r);
  assert.equal(r.canonical_role, 'Researcher');
});

run('PR-03 GP at Acme Ventures, $50M fund -> Investor', () => {
  const r = parseRoleHints('GP at Acme Ventures, $50M fund');
  assert.ok(r);
  assert.equal(r.canonical_role, 'Investor');
});

run('PR-04 plain prose with no role hints -> null', () => {
  const r = parseRoleHints('I have been thinking about market fit lately and the next quarter feels uncertain.');
  assert.equal(r, null);
});

run('PR-null null input -> null', () => {
  const r = parseRoleHints(null);
  assert.equal(r, null);
});

// ---------- parseVentureHint (3 fixtures) ----------

run('PV-01 Founder of Acme Robotics -> Acme Robotics', () => {
  const r = parseVentureHint('Founder of Acme Robotics');
  assert.equal(r.name, 'Acme Robotics');
  assert.equal(r.stage, 'unknown');
});

run('PV-02 PI on NCT12345678 -> clinical-trial', () => {
  const r = parseVentureHint('PI on NCT12345678 clinical trial');
  assert.equal(r.name, 'NCT12345678');
  assert.equal(r.stage, 'clinical-trial');
});

run('PV-03 plain prose graceful degradation -> null name', () => {
  const r = parseVentureHint("I'm working on something");
  assert.equal(r.name, null);
  assert.equal(r.stage, 'unknown');
});

run('PV-null null input -> null name', () => {
  const r = parseVentureHint(null);
  assert.equal(r.name, null);
  assert.equal(r.stage, 'unknown');
});

// ---------- parseClaims (1 fixture) ----------

run('PC-01 CV with 3 bullets -> 3 claim objects', () => {
  const text = '- Founded Acme in 2024\n- Raised $5M Series A\n- Team of 8 engineers and operators';
  const claims = parseClaims(text);
  assert.equal(claims.length, 3);
  assert.ok(claims[0].text.length > 0);
  assert.ok(claims[1].text.length > 0);
  assert.ok(claims[2].text.length > 0);
  assert.match(claims[0].text, /Founded Acme in 2024/);
});

run('PC-null null input -> empty array', () => {
  const r = parseClaims(null);
  assert.deepEqual(r, []);
});

// ---------- extractShallow integration (ES-01 happy-path) ----------

run('ES-01 full CV paste -> 1 user + 1 venture + 3 claims, navigation calls', () => {
  navStub.__reset();
  const text = [
    'Founder of Acme Robotics',
    'PhD MIT 2018',
    'NIH SBIR $2M 2023',
    '',
    '- Founded Acme in 2024',
    '- Raised Seed round 2024',
    '- Team of 6 engineers',
  ].join('\n');
  const t0 = Date.now();
  const r = extractShallow(text, 'session-test-1');
  const elapsed = Date.now() - t0;

  // Result shape
  assert.ok(r.user, 'expected user node, got ' + JSON.stringify(r.user));
  assert.equal(r.user.canonical_role, 'Founder');
  assert.ok(r.venture, 'expected venture node');
  assert.equal(r.venture.name, 'Acme Robotics');
  assert.ok(Array.isArray(r.claims));
  assert.equal(r.claims.length, 3);

  // Navigation calls: setFocus called exactly once for venture
  assert.equal(navStub.__calls.setFocus.length, 1);
  assert.equal(navStub.__calls.setFocus[0].sid, 'session-test-1');
  assert.equal(navStub.__calls.setFocus[0].sb, 'auto-from-upload');

  // Navigation calls: 5 node_created memory events (1 user + 1 venture + 3 claims)
  assert.equal(navStub.__calls.memoryEvents.length, 5,
    'expected 5 memory events, got ' + navStub.__calls.memoryEvents.length);
  for (const ev of navStub.__calls.memoryEvents) {
    assert.equal(ev.type, 'node_created');
    assert.equal(ev.sid, 'session-test-1');
  }

  // Performance budget (sanity)
  assert.ok(elapsed < 100, 'extractShallow took ' + elapsed + 'ms, expected < 100');
});

// ---------- extractShallow graceful degradation (ES-02) ----------

run('ES-02 garbage input -> 0 nodes, 0 memory events, no throw', () => {
  navStub.__reset();
  const r = extractShallow('asdfqwerty 123 !@#$%^&*()_+', 'session-test-garbage');
  assert.equal(r.user, null);
  assert.equal(r.venture, null);
  assert.deepEqual(r.claims, []);
  assert.equal(navStub.__calls.setFocus.length, 0);
  assert.equal(navStub.__calls.memoryEvents.length, 0);
});

run('ES-null missing sessionId -> empty result, no navigation calls', () => {
  navStub.__reset();
  const r = extractShallow('Founder of Acme Robotics', '');
  assert.equal(r.user, null);
  assert.equal(r.venture, null);
  assert.deepEqual(r.claims, []);
  assert.equal(navStub.__calls.setFocus.length, 0);
});

run('ES-null2 null text -> empty result', () => {
  navStub.__reset();
  const r = extractShallow(null, 'session-x');
  assert.equal(r.user, null);
  assert.equal(r.venture, null);
  assert.deepEqual(r.claims, []);
});

// ---------- Summary ----------

process.stdout.write('\nshallow-doc-parser: ' + passed + '/' + (passed + failed) + ' passed, ' + failed + ' failed\n');
process.exit(failed === 0 ? 0 : 1);
